# db/repository.py
"""
The single data-access surface core/booking_flow.py and reminders/scheduler.py
talk to (SPEC Section 12.6 Tier 1) — no raw SQL anywhere outside this file.
Every function that reads/writes hospital-scoped data takes hospital_id and
filters by it (SPEC Section 12.2: "no query should ever return or write data
without this filter").

get_slots()/find_slot() read real, persisted rows from doctor_slots (Section
12.1.1) generated by generate_slots_for_doctor() from each doctor's working
pattern (working_days/working_hours/slot_duration_minutes) — no more
synthetic/computed-on-the-fly slots. As of Phase 8 they still exclude slots
that already have a *booked* appointment, so an already-taken slot is never
re-offered to another patient.
"""
import json as json_lib
import uuid
from dataclasses import dataclass
from datetime import date, datetime, timedelta

from db.connection import get_connection

STATUS_BOOKED = "booked"
STATUS_CANCELLED = "cancelled"
STATUS_RESCHEDULED = "rescheduled"

_SLOT_DAYS_AHEAD = 14

_WEEKDAY_ABBREVS = ("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")

_APPOINTMENT_SELECT = """
    SELECT a.id, a.hospital_id, a.phone, a.department_id, d.name AS department_name,
           a.doctor_id, doc.name AS doctor_name, a.scheduled_at, a.status
    FROM appointments a
    JOIN departments d ON d.id = a.department_id
    JOIN doctors doc ON doc.id = a.doctor_id
"""


@dataclass
class Appointment:
    id: int
    hospital_id: int
    phone: str
    department_id: str
    department_name: str
    doctor_id: str
    doctor_name: str
    scheduled_at: datetime
    status: str = STATUS_BOOKED


def _row_to_appointment(row) -> Appointment:
    return Appointment(
        id=row["id"],
        hospital_id=row["hospital_id"],
        phone=row["phone"],
        department_id=row["department_id"],
        department_name=row["department_name"],
        doctor_id=row["doctor_id"],
        doctor_name=row["doctor_name"],
        scheduled_at=datetime.fromisoformat(row["scheduled_at"]),
        status=row["status"],
    )


# --- Hospitals (SPEC Section 12.2: multi-tenant routing, Phase 9) ---

@dataclass
class Hospital:
    id: int
    name: str
    whatsapp_phone_number_id: str | None
    access_token: str | None  # DB column: meta_access_token_ref
    app_secret: str | None  # DB column: app_secret_ref
    timezone: str
    welcome_message_text: str | None
    reminder_offsets_hours: list[float]
    reminder_template_name: str | None
    is_active: bool
    data_tier: str
    external_api_base_url: str | None
    external_api_key: str | None


def _row_to_hospital(row) -> Hospital:
    try:
        offsets = json_lib.loads(row["reminder_offsets_hours"])
        if not isinstance(offsets, list) or not offsets:
            raise ValueError
    except (TypeError, ValueError):
        offsets = [24]
    return Hospital(
        id=row["id"],
        name=row["name"],
        whatsapp_phone_number_id=row["whatsapp_phone_number_id"],
        access_token=row["meta_access_token_ref"],
        app_secret=row["app_secret_ref"],
        timezone=row["timezone"],
        welcome_message_text=row["welcome_message_text"],
        reminder_offsets_hours=offsets,
        reminder_template_name=row["reminder_template_name"],
        is_active=bool(row["is_active"]),
        data_tier=row["data_tier"],
        external_api_base_url=row["external_api_base_url"],
        external_api_key=row["external_api_key"],
    )


def find_hospital_by_phone_number_id(phone_number_id: str) -> Hospital | None:
    """The entry point for per-message multi-tenant routing (SPEC Section 12.2):
    given the phone_number_id from an incoming webhook's `metadata`, resolve which
    hospital received it. Only active hospitals are matched — a deactivated
    hospital's number should be treated the same as an unrecognized one."""
    conn = get_connection()
    row = conn.execute(
        "SELECT * FROM hospitals WHERE whatsapp_phone_number_id = ? AND is_active = 1",
        (phone_number_id,),
    ).fetchone()
    return _row_to_hospital(row) if row else None


def get_active_hospitals() -> list[Hospital]:
    """Used by reminders/scheduler.py's caller (core/main.py) to loop over every
    active hospital rather than a single startup-resolved one."""
    conn = get_connection()
    rows = conn.execute("SELECT * FROM hospitals WHERE is_active = 1 ORDER BY id").fetchall()
    return [_row_to_hospital(r) for r in rows]


def get_hospital(hospital_id: int) -> Hospital | None:
    conn = get_connection()
    row = conn.execute("SELECT * FROM hospitals WHERE id = ?", (hospital_id,)).fetchone()
    return _row_to_hospital(row) if row else None


def create_hospital(
    name: str,
    whatsapp_phone_number_id: str,
    access_token: str | None = None,
    app_secret: str | None = None,
    timezone: str = "UTC",
    welcome_message_text: str | None = None,
    reminder_offsets_hours: list[float] | None = None,
    reminder_template_name: str | None = None,
    data_tier: str = "tier1",
    external_api_base_url: str | None = None,
    external_api_key: str | None = None,
) -> Hospital:
    """Onboarding wizard's entry point (SPEC Section 12.1, Phase 10). Raises
    db.connection.IntegrityError if whatsapp_phone_number_id is already used by
    another hospital -- db/schema.sql's UNIQUE constraint is the actual guard
    against breaking Phase 9's per-message routing, not application logic;
    callers (admin/onboarding.py) are responsible for catching it.

    data_tier (Section 12.6, Step 6 of the wizard): "tier1" (default, this
    product's own database), "tier2" (external_api_base_url/external_api_key
    are only stored here -- no connector logic reads them yet), or "tier3"
    (direct DB connection, not self-serve -- neither field is meaningful for it)."""
    conn = get_connection()
    offsets_json = json_lib.dumps(reminder_offsets_hours or [24])
    cur = conn.execute(
        "INSERT INTO hospitals (name, whatsapp_phone_number_id, meta_access_token_ref, app_secret_ref, "
        "timezone, welcome_message_text, reminder_offsets_hours, reminder_template_name, "
        "data_tier, external_api_base_url, external_api_key) "
        "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id",
        (name, whatsapp_phone_number_id, access_token, app_secret, timezone,
         welcome_message_text, offsets_json, reminder_template_name,
         data_tier, external_api_base_url, external_api_key),
    )
    new_id = cur.fetchone()["id"]
    conn.commit()
    return get_hospital(new_id)


# --- Departments / doctors ---

def get_departments(hospital_id: int) -> list[dict]:
    conn = get_connection()
    rows = conn.execute(
        "SELECT id, name FROM departments WHERE hospital_id = ? ORDER BY name",
        (hospital_id,),
    ).fetchall()
    return [dict(r) for r in rows]


def find_department(hospital_id: int, department_id: str) -> dict | None:
    conn = get_connection()
    row = conn.execute(
        "SELECT id, name FROM departments WHERE hospital_id = ? AND id = ?",
        (hospital_id, department_id),
    ).fetchone()
    return dict(row) if row else None


def get_doctors(hospital_id: int, department_id: str) -> list[dict]:
    conn = get_connection()
    rows = conn.execute(
        "SELECT id, name FROM doctors WHERE hospital_id = ? AND department_id = ? ORDER BY name",
        (hospital_id, department_id),
    ).fetchall()
    return [dict(r) for r in rows]


def find_doctor(hospital_id: int, department_id: str, doctor_id: str) -> dict | None:
    conn = get_connection()
    row = conn.execute(
        "SELECT id, name FROM doctors WHERE hospital_id = ? AND department_id = ? AND id = ?",
        (hospital_id, department_id, doctor_id),
    ).fetchone()
    return dict(row) if row else None


def create_department(hospital_id: int, name: str) -> dict:
    """id is a UUID-derived opaque string (not a slug of `name`), scoped by an
    h{hospital_id}_ prefix -- avoids both the collision risk of slugifying
    arbitrary user-entered text and the known Tier 1 limitation that
    departments.id is globally unique, not (hospital_id, id) composite-unique
    (db/schema.sql's comment on that table)."""
    department_id = f"h{hospital_id}_{uuid.uuid4().hex[:8]}"
    conn = get_connection()
    conn.execute(
        "INSERT INTO departments (id, hospital_id, name) VALUES (?, ?, ?)",
        (department_id, hospital_id, name),
    )
    conn.commit()
    return {"id": department_id, "name": name}


def create_doctor(
    hospital_id: int,
    department_id: str,
    name: str,
    specialization: str | None = None,
    qualification: str | None = None,
    years_experience: int | None = None,
    working_days: list[str] | None = None,
    working_hours: list[str] | None = None,
    slot_duration_minutes: int = 30,
) -> dict:
    """working_days (e.g. ["Mon", "Wed", "Fri"]) and working_hours (e.g.
    ["10:00-13:00", "17:00-20:00"]) are this doctor's working pattern (Section
    12.1 Step 7) -- generate_slots_for_doctor() is called immediately below to
    produce the initial rolling window of real doctor_slots rows from it
    (Section 12.1.1), so onboarding a doctor through this function is what
    "run slot generation at onboarding submission time" means in practice. A
    doctor with no working_days/working_hours simply generates zero slots."""
    doctor_id = f"h{hospital_id}_{uuid.uuid4().hex[:8]}"
    conn = get_connection()
    conn.execute(
        "INSERT INTO doctors (id, hospital_id, department_id, name, specialization, qualification, "
        "years_experience, working_days, working_hours, slot_duration_minutes) "
        "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        (doctor_id, hospital_id, department_id, name, specialization, qualification,
         years_experience, ",".join(working_days or []), ",".join(working_hours or []), slot_duration_minutes),
    )
    conn.commit()
    generate_slots_for_doctor(hospital_id, doctor_id, conn=conn)
    return {"id": doctor_id, "name": name}


def list_doctor_ids(hospital_id: int) -> list[str]:
    """Used by the slot top-up job (slots/scheduler.py) to loop every doctor
    at a hospital without needing to walk departments first."""
    conn = get_connection()
    rows = conn.execute("SELECT id FROM doctors WHERE hospital_id = ?", (hospital_id,)).fetchall()
    return [r["id"] for r in rows]


def _parse_time_range(time_range: str) -> tuple[str, str]:
    start, end = time_range.split("-")
    return start.strip(), end.strip()


def generate_slots_for_doctor(
    hospital_id: int,
    doctor_id: str,
    days_ahead: int = _SLOT_DAYS_AHEAD,
    now: date | None = None,
    conn=None,
) -> int:
    """Generates real doctor_slots rows for the next `days_ahead` days (Section
    12.1.1) from this doctor's stored working_days/working_hours/
    slot_duration_minutes. ON CONFLICT DO NOTHING against doctor_slots' UNIQUE
    (doctor_id, scheduled_at) (db/schema.sql) is what makes this idempotent --
    calling it again for a window that's already partly populated (the
    periodic top-up job, slots/scheduler.py) only adds the new days, never
    duplicates existing ones. Returns the number of *new* slot rows inserted.

    conn is an optional explicit connection (rather than get_connection())
    because db/seed.py calls this against a connection it's still assembling,
    before db.connection's shared connection has been repointed to it."""
    conn = conn or get_connection()
    doctor_row = conn.execute(
        "SELECT working_days, working_hours, slot_duration_minutes FROM doctors WHERE hospital_id = ? AND id = ?",
        (hospital_id, doctor_id),
    ).fetchone()
    if doctor_row is None:
        return 0

    working_days = {d.strip() for d in doctor_row["working_days"].split(",") if d.strip()}
    working_hours = [h.strip() for h in doctor_row["working_hours"].split(",") if h.strip()]
    slot_duration = doctor_row["slot_duration_minutes"]
    if not working_days or not working_hours or not slot_duration:
        return 0

    today = now or date.today()
    inserted = 0
    for i in range(1, days_ahead + 1):
        d = today + timedelta(days=i)
        if _WEEKDAY_ABBREVS[d.weekday()] not in working_days:
            continue
        for time_range in working_hours:
            start_str, end_str = _parse_time_range(time_range)
            current = datetime.combine(d, datetime.strptime(start_str, "%H:%M").time())
            end = datetime.combine(d, datetime.strptime(end_str, "%H:%M").time())
            step = timedelta(minutes=slot_duration)
            while current + step <= end:
                cur = conn.execute(
                    "INSERT INTO doctor_slots (hospital_id, doctor_id, scheduled_at) VALUES (?, ?, ?) "
                    "ON CONFLICT (doctor_id, scheduled_at) DO NOTHING",
                    (hospital_id, doctor_id, current.isoformat()),
                )
                inserted += cur.rowcount
                current += step
    conn.commit()
    return inserted


# --- Slots (real, persisted rows — see module docstring) ---

def get_slots(hospital_id: int, doctor_id: str) -> list[dict]:
    """This doctor's generated doctor_slots rows, minus any that already have a
    *booked* appointment at that exact time (Phase 8: an already-taken slot
    must never be offered to another patient)."""
    conn = get_connection()
    booked_rows = conn.execute(
        "SELECT scheduled_at FROM appointments WHERE hospital_id = ? AND doctor_id = ? AND status = ?",
        (hospital_id, doctor_id, STATUS_BOOKED),
    ).fetchall()
    booked_at = {row["scheduled_at"] for row in booked_rows}

    slot_rows = conn.execute(
        "SELECT scheduled_at FROM doctor_slots WHERE hospital_id = ? AND doctor_id = ? ORDER BY scheduled_at",
        (hospital_id, doctor_id),
    ).fetchall()

    slots = []
    for row in slot_rows:
        scheduled_at_iso = row["scheduled_at"]
        if scheduled_at_iso in booked_at:
            continue
        dt = datetime.fromisoformat(scheduled_at_iso)
        slots.append({
            "id": scheduled_at_iso,
            "date": dt.date().isoformat(),
            "time": dt.strftime("%H:%M"),
            "label": f"{dt.strftime('%a %d %b')} {dt.strftime('%H:%M')}",
        })
    return slots


def find_slot(hospital_id: int, doctor_id: str, slot_id: str) -> dict | None:
    for s in get_slots(hospital_id, doctor_id):
        if s["id"] == slot_id:
            return s
    return None


# --- Appointments ---

def create_appointment(
    hospital_id: int,
    phone: str,
    department_id: str,
    doctor_id: str,
    scheduled_at: datetime,
) -> Appointment:
    """Raises db.connection.IntegrityError if this doctor already has a
    *booked* appointment at this exact scheduled_at (db/schema.sql's partial
    unique index) — that's the actual double-booking guard, not application
    logic. Catching it gracefully is Phase 8 work, not done here."""
    conn = get_connection()
    cur = conn.execute(
        "INSERT INTO appointments (hospital_id, phone, department_id, doctor_id, scheduled_at) "
        "VALUES (?, ?, ?, ?, ?) RETURNING id",
        (hospital_id, phone, department_id, doctor_id, scheduled_at.isoformat()),
    )
    new_id = cur.fetchone()["id"]
    conn.commit()
    return get_appointment(hospital_id, new_id)


def get_appointment(hospital_id: int, appointment_id: int) -> Appointment | None:
    conn = get_connection()
    row = conn.execute(
        _APPOINTMENT_SELECT + " WHERE a.id = ? AND a.hospital_id = ?",
        (appointment_id, hospital_id),
    ).fetchone()
    return _row_to_appointment(row) if row else None


def get_upcoming_appointments_for_phone(hospital_id: int, phone: str, now: datetime | None = None) -> list[Appointment]:
    """A patient's own future, still-booked appointments — soonest first.
    Past appointments and ones already cancelled/rescheduled are excluded here
    (not filtered later) so callers never have to remember to check status."""
    now = now or datetime.now()
    conn = get_connection()
    rows = conn.execute(
        _APPOINTMENT_SELECT + " WHERE a.hospital_id = ? AND a.phone = ? AND a.status = ? AND a.scheduled_at > ? "
        "ORDER BY a.scheduled_at ASC",
        (hospital_id, phone, STATUS_BOOKED, now.isoformat()),
    ).fetchall()
    return [_row_to_appointment(r) for r in rows]


def get_upcoming_appointments(hospital_id: int, offset_hours: float, now: datetime | None = None) -> list[Appointment]:
    """Still-booked appointments scheduled between `now` and `now + offset_hours`
    that haven't had a reminder sent yet *for this specific offset* — a hospital
    can configure multiple offsets (SPEC Section 4's reminder_offsets_hours, e.g.
    24h-before AND 1h-before), each tracked independently via appointment_reminders
    so configuring more than one actually results in more than one reminder per
    appointment, rather than the first one sent silently blocking the rest.
    Used by reminders/scheduler.py, once per offset."""
    now = now or datetime.now()
    cutoff = now + timedelta(hours=offset_hours)
    conn = get_connection()
    rows = conn.execute(
        _APPOINTMENT_SELECT + """
        WHERE a.hospital_id = ? AND a.status = ?
          AND a.scheduled_at >= ? AND a.scheduled_at <= ?
          AND NOT EXISTS (
              SELECT 1 FROM appointment_reminders ar
              WHERE ar.appointment_id = a.id AND ar.offset_hours = ?
          )
        ORDER BY a.scheduled_at ASC
        """,
        (hospital_id, STATUS_BOOKED, now.isoformat(), cutoff.isoformat(), offset_hours),
    ).fetchall()
    return [_row_to_appointment(r) for r in rows]


def mark_reminded(hospital_id: int, appointment_id: int, offset_hours: float) -> None:
    """Records that the reminder for this specific offset has been sent.
    ON CONFLICT DO NOTHING + appointment_reminders' UNIQUE(appointment_id, offset_hours)
    (db/schema.sql) means calling this twice for the same offset is a safe no-op,
    not a duplicate record — that constraint is the actual no-double-send
    guarantee, same pattern as the double-booking index from Phase 8."""
    conn = get_connection()
    conn.execute(
        "INSERT INTO appointment_reminders (hospital_id, appointment_id, offset_hours) VALUES (?, ?, ?) "
        "ON CONFLICT (appointment_id, offset_hours) DO NOTHING",
        (hospital_id, appointment_id, offset_hours),
    )
    conn.commit()


def get_reminded_offsets(hospital_id: int, appointment_id: int) -> list[float]:
    """Which reminder offsets (in hours) have already fired for this appointment."""
    conn = get_connection()
    rows = conn.execute(
        "SELECT offset_hours FROM appointment_reminders WHERE hospital_id = ? AND appointment_id = ? ORDER BY offset_hours DESC",
        (hospital_id, appointment_id),
    ).fetchall()
    return [r["offset_hours"] for r in rows]


def cancel_appointment(hospital_id: int, appointment_id: int) -> None:
    """Marks the appointment cancelled — does not delete the row, so
    cancellation history/audit trail isn't lost."""
    conn = get_connection()
    conn.execute(
        "UPDATE appointments SET status = ? WHERE id = ? AND hospital_id = ?",
        (STATUS_CANCELLED, appointment_id, hospital_id),
    )
    conn.commit()


def mark_rescheduled(hospital_id: int, appointment_id: int) -> None:
    """Marks the old appointment as superseded by a reschedule — does not
    delete the row. Callers are responsible for create_appointment()-ing the
    new slot separately (see core/booking_flow.py's reschedule confirm)."""
    conn = get_connection()
    conn.execute(
        "UPDATE appointments SET status = ? WHERE id = ? AND hospital_id = ?",
        (STATUS_RESCHEDULED, appointment_id, hospital_id),
    )
    conn.commit()
