# db/repository.py
"""
The single data-access surface core/booking_flow.py and reminders/scheduler.py
talk to (SPEC Section 12.6 Tier 1) — no raw SQL anywhere outside this file.
Every function that reads/writes hospital-scoped data takes hospital_id and
filters by it (SPEC Section 12.2: "no query should ever return or write data
without this filter").

get_slots()/find_slot() read real, persisted rows from doctor_slots (Section
12.1.1) generated by generate_slots_for_doctor() from each doctor's working
pattern (working_days/working_hours/slot_duration_minutes) — no more
synthetic/computed-on-the-fly slots. As of Phase 8 they still exclude slots
that already have a *booked* appointment, so an already-taken slot is never
re-offered to another patient.
"""
import hashlib
import hmac
import json as json_lib
import os
import uuid
from dataclasses import dataclass
from datetime import date, datetime, timedelta

from db.connection import IntegrityError, get_connection

STATUS_BOOKED = "booked"
STATUS_CANCELLED = "cancelled"
STATUS_RESCHEDULED = "rescheduled"

SOURCE_WHATSAPP = "whatsapp"
SOURCE_STAFF = "staff"


class QuotaExceededError(IntegrityError):
    """Section 12.9: raised by create_appointment() specifically when a
    booking is rejected because the doctor's online_quota/walkin_quota/
    daily_booking_limit (Section 14.7) is exhausted, as opposed to the exact
    requested slot being full. Subclasses IntegrityError so every EXISTING
    `except IntegrityError:` call site (core/booking_flow.py's double-booking
    handling) keeps working unchanged with its generic "that slot was just
    taken" message; portal.py's staff-booking route catches THIS specifically
    first, to show str(e) (a purpose-written message) instead."""

_SLOT_DAYS_AHEAD = 14

_WEEKDAY_ABBREVS = ("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")

_APPOINTMENT_SELECT = """
    SELECT a.id, a.hospital_id, a.phone, a.department_id, d.name AS department_name,
           a.doctor_id, doc.name AS doctor_name, a.scheduled_at, a.status, a.source
    FROM appointments a
    JOIN departments d ON d.id = a.department_id
    JOIN doctors doc ON doc.id = a.doctor_id
"""


@dataclass
class Appointment:
    id: int
    hospital_id: int
    phone: str
    department_id: str
    department_name: str
    doctor_id: str
    doctor_name: str
    scheduled_at: datetime
    status: str = STATUS_BOOKED
    # Section 12.9: 'whatsapp' (patient self-booking) or 'staff' (portal.py's
    # /portal/new-booking) -- descriptive only, never branched on by booking
    # logic itself (both go through the exact same create_appointment()).
    source: str = "whatsapp"


def _row_to_appointment(row) -> Appointment:
    return Appointment(
        id=row["id"],
        hospital_id=row["hospital_id"],
        phone=row["phone"],
        department_id=row["department_id"],
        department_name=row["department_name"],
        doctor_id=row["doctor_id"],
        doctor_name=row["doctor_name"],
        scheduled_at=datetime.fromisoformat(row["scheduled_at"]),
        status=row["status"],
        source=row["source"],
    )


# --- Hospitals (SPEC Section 12.2: multi-tenant routing, Phase 9) ---

_PBKDF2_ITERATIONS = 100_000


def hash_portal_password(password: str) -> str:
    """Salted PBKDF2-SHA256, stdlib only (no new dependency for what's still a
    'basic protection, not production-grade auth' project) -- used for the
    Section 12.7 hospital-staff bookings portal login, which is stored as an
    irreversible hash (unlike access_token/app_secret, which the app must be
    able to read back to call Meta's API with -- a login password never needs
    to be reversed, only verified, so there's no reason to store it in a
    reversible form the way those are). Stored as 'salt_hex:hash_hex'."""
    salt = os.urandom(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode(), salt, _PBKDF2_ITERATIONS)
    return f"{salt.hex()}:{digest.hex()}"


def verify_portal_password(password: str, stored_hash: str) -> bool:
    try:
        salt_hex, digest_hex = stored_hash.split(":", 1)
    except (ValueError, AttributeError):
        return False
    salt = bytes.fromhex(salt_hex)
    candidate = hashlib.pbkdf2_hmac("sha256", password.encode(), salt, _PBKDF2_ITERATIONS)
    return hmac.compare_digest(candidate.hex(), digest_hex)


@dataclass
class Hospital:
    id: int
    name: str
    whatsapp_phone_number_id: str | None
    access_token: str | None  # DB column: meta_access_token_ref
    app_secret: str | None  # DB column: app_secret_ref
    timezone: str
    welcome_message_text: str | None
    reminder_offsets_hours: list[float]
    reminder_template_name: str | None
    is_active: bool
    data_tier: str
    external_api_base_url: str | None
    external_api_key: str | None
    portal_password_hash: str | None
    enabled_features: list[str]


def _row_to_hospital(row) -> Hospital:
    try:
        offsets = json_lib.loads(row["reminder_offsets_hours"])
        if not isinstance(offsets, list) or not offsets:
            raise ValueError
    except (TypeError, ValueError):
        offsets = [24]
    try:
        enabled_features = json_lib.loads(row["enabled_features"])
        if not isinstance(enabled_features, list):
            raise ValueError
    except (TypeError, ValueError):
        # NULL (not yet backfilled -- db/init_db.py's _backfill_enabled_features()
        # should have already run by the time anything queries this, but fail
        # safe to "nothing enabled" rather than crash a row read) or malformed.
        enabled_features = []
    return Hospital(
        id=row["id"],
        name=row["name"],
        whatsapp_phone_number_id=row["whatsapp_phone_number_id"],
        access_token=row["meta_access_token_ref"],
        app_secret=row["app_secret_ref"],
        timezone=row["timezone"],
        welcome_message_text=row["welcome_message_text"],
        reminder_offsets_hours=offsets,
        reminder_template_name=row["reminder_template_name"],
        is_active=bool(row["is_active"]),
        data_tier=row["data_tier"],
        external_api_base_url=row["external_api_base_url"],
        external_api_key=row["external_api_key"],
        portal_password_hash=row["portal_password_hash"],
        enabled_features=enabled_features,
    )


def find_hospital_by_phone_number_id(phone_number_id: str) -> Hospital | None:
    """The entry point for per-message multi-tenant routing (SPEC Section 12.2):
    given the phone_number_id from an incoming webhook's `metadata`, resolve which
    hospital received it. Only active hospitals are matched — a deactivated
    hospital's number should be treated the same as an unrecognized one."""
    conn = get_connection()
    row = conn.execute(
        "SELECT * FROM hospitals WHERE whatsapp_phone_number_id = ? AND is_active = 1",
        (phone_number_id,),
    ).fetchone()
    return _row_to_hospital(row) if row else None


def get_active_hospitals() -> list[Hospital]:
    """Used by reminders/scheduler.py's caller (core/main.py) to loop over every
    active hospital rather than a single startup-resolved one."""
    conn = get_connection()
    rows = conn.execute("SELECT * FROM hospitals WHERE is_active = 1 ORDER BY id").fetchall()
    return [_row_to_hospital(r) for r in rows]


def get_all_hospitals() -> list[Hospital]:
    """Every hospital regardless of is_active -- admin/onboarding.py's tenant
    list page (Section 12.1 follow-up: closing the "onboarding is self-serve,
    correcting it isn't" gap) needs to show every onboarded tenant, not just
    active ones, so there's somewhere to find a deactivated tenant's id too."""
    conn = get_connection()
    rows = conn.execute("SELECT * FROM hospitals ORDER BY id").fetchall()
    return [_row_to_hospital(r) for r in rows]


def get_hospital(hospital_id: int) -> Hospital | None:
    conn = get_connection()
    row = conn.execute("SELECT * FROM hospitals WHERE id = ?", (hospital_id,)).fetchone()
    return _row_to_hospital(row) if row else None


def find_hospital_by_portal_password(password: str) -> Hospital | None:
    """portal.py's login: which hospital does this password belong to. Each
    hash carries its own random salt (hash_portal_password()), so two
    hospitals CAN pick the identical password and still get different stored
    hashes -- there's no way to look one up by an equality WHERE clause, only
    by hashing the candidate against every stored hash and checking for a
    match. Fine at this project's scale (dozens/hundreds of hospitals, not
    millions); an actual login-throughput bottleneck would need a different
    scheme, but isn't a real concern yet."""
    for hospital in get_all_hospitals():
        if hospital.portal_password_hash and hospital.is_active:
            if verify_portal_password(password, hospital.portal_password_hash):
                return hospital
    return None


def create_hospital(
    name: str,
    whatsapp_phone_number_id: str,
    access_token: str | None = None,
    app_secret: str | None = None,
    timezone: str = "UTC",
    welcome_message_text: str | None = None,
    reminder_offsets_hours: list[float] | None = None,
    reminder_template_name: str | None = None,
    data_tier: str = "tier1",
    external_api_base_url: str | None = None,
    external_api_key: str | None = None,
    portal_password: str | None = None,
    enabled_features: list[str] | None = None,
) -> Hospital:
    """Onboarding wizard's entry point (SPEC Section 12.1, Phase 10). Raises
    db.connection.IntegrityError if whatsapp_phone_number_id is already used by
    another hospital -- db/schema.sql's UNIQUE constraint is the actual guard
    against breaking Phase 9's per-message routing, not application logic;
    callers (admin/onboarding.py) are responsible for catching it.

    data_tier (Section 12.6, Step 0 of the wizard as of Section 14.6's
    reorder): "tier1" (default, this product's own database), "tier2"
    (external_api_base_url/external_api_key are only stored here -- no
    connector logic reads them yet), or "tier3" (direct DB connection, not
    self-serve -- neither field is meaningful for it).

    portal_password (Section 12.7): plaintext in, hashed before storage --
    optional at onboarding time (a hospital can set it later via the edit
    form); left unset, the bookings portal simply has no way to log into that
    hospital yet.

    enabled_features (Section 14.5): the set of patient-facing capabilities
    this hospital's WhatsApp number offers (e.g. ["booking","reschedule",
    "cancel","faq"]) -- flows.py's IDLE main menu shows only these. Replaces
    the earlier single-value flow_type (Section 14.1); defaults to an empty
    list (no capabilities enabled) rather than guessing "booking", since an
    empty set is a safe, honest default a caller has to deliberately override,
    not a value that quietly implies functionality nothing configured yet."""
    conn = get_connection()
    offsets_json = json_lib.dumps(reminder_offsets_hours or [24])
    features_json = json_lib.dumps(enabled_features or [])
    portal_password_hash = hash_portal_password(portal_password) if portal_password else None
    cur = conn.execute(
        "INSERT INTO hospitals (name, whatsapp_phone_number_id, meta_access_token_ref, app_secret_ref, "
        "timezone, welcome_message_text, reminder_offsets_hours, reminder_template_name, "
        "data_tier, external_api_base_url, external_api_key, portal_password_hash, enabled_features) "
        "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id",
        (name, whatsapp_phone_number_id, access_token, app_secret, timezone,
         welcome_message_text, offsets_json, reminder_template_name,
         data_tier, external_api_base_url, external_api_key, portal_password_hash, features_json),
    )
    new_id = cur.fetchone()["id"]
    conn.commit()
    return get_hospital(new_id)


def update_hospital(
    hospital_id: int,
    name: str,
    whatsapp_phone_number_id: str,
    access_token: str | None = None,
    app_secret: str | None = None,
    timezone: str = "UTC",
    welcome_message_text: str | None = None,
    reminder_offsets_hours: list[float] | None = None,
    reminder_template_name: str | None = None,
    data_tier: str = "tier1",
    external_api_base_url: str | None = None,
    external_api_key: str | None = None,
    portal_password_hash: str | None = None,
    enabled_features: list[str] | None = None,
) -> Hospital:
    """admin/onboarding.py's tenant edit form -- the only way to correct an
    already-onboarded hospital's stored values (there's no way to change
    departments/doctors here, only the hospitals row itself). Raises
    db.connection.IntegrityError if whatsapp_phone_number_id is changed to a
    value another hospital already uses -- same UNIQUE constraint create_hospital()
    relies on; a hospital keeping its own existing phone_number_id unchanged
    never conflicts with itself. Callers (admin/onboarding.py) are responsible
    for catching it, same as create_hospital().

    portal_password_hash takes an ALREADY-HASHED value (or the hospital's
    existing one, to leave it unchanged) -- unlike create_hospital(), which
    takes a raw password, because the edit route needs to decide whether a
    blank submitted field means "keep current hash" *before* this function
    ever sees it (hashing here would turn a blank field into a real password).

    Deliberately does NOT touch _wa_clients (core/main.py's per-hospital
    WhatsAppClient cache) -- it can't, from here; a hospital whose credentials
    just changed keeps using its OLD cached client until the process restarts.
    See core/main.py's _wa_clients comment and the post-edit confirmation page.

    enabled_features (Section 14.5) defaults to an empty list like
    create_hospital(), but every caller (admin/onboarding.py's edit-tenant
    route, portal.py's settings route) passes the hospital's own current
    value through explicitly -- neither exposes a way to CHANGE which
    features are enabled yet, so an edit to something else must never
    silently reset a tenant's real feature set back to empty."""
    conn = get_connection()
    offsets_json = json_lib.dumps(reminder_offsets_hours or [24])
    features_json = json_lib.dumps(enabled_features or [])
    conn.execute(
        "UPDATE hospitals SET name = ?, whatsapp_phone_number_id = ?, meta_access_token_ref = ?, "
        "app_secret_ref = ?, timezone = ?, welcome_message_text = ?, reminder_offsets_hours = ?, "
        "reminder_template_name = ?, data_tier = ?, external_api_base_url = ?, external_api_key = ?, "
        "portal_password_hash = ?, enabled_features = ? WHERE id = ?",
        (name, whatsapp_phone_number_id, access_token, app_secret, timezone,
         welcome_message_text, offsets_json, reminder_template_name,
         data_tier, external_api_base_url, external_api_key, portal_password_hash, features_json, hospital_id),
    )
    conn.commit()
    return get_hospital(hospital_id)


# --- Departments / doctors ---

def get_departments(hospital_id: int) -> list[dict]:
    conn = get_connection()
    rows = conn.execute(
        "SELECT id, name FROM departments WHERE hospital_id = ? ORDER BY name",
        (hospital_id,),
    ).fetchall()
    return [dict(r) for r in rows]


def find_department(hospital_id: int, department_id: str) -> dict | None:
    conn = get_connection()
    row = conn.execute(
        "SELECT id, name FROM departments WHERE hospital_id = ? AND id = ?",
        (hospital_id, department_id),
    ).fetchone()
    return dict(row) if row else None


def get_doctors(hospital_id: int, department_id: str) -> list[dict]:
    """The connector interface's own get_doctors() (Section 12.6.2) -- both
    the WhatsApp bot's booking flow AND the staff portal's new-booking page
    read doctor lists through this one function, so excluding is_active=FALSE
    doctors here is the single enforcement point for "staff turned this
    doctor off" everywhere a booking could actually be created, not just the
    bot. The portal's own doctor MANAGEMENT list uses
    get_all_doctors_for_hospital() instead, which intentionally still shows
    inactive doctors so staff can toggle them back on."""
    conn = get_connection()
    rows = conn.execute(
        "SELECT id, name FROM doctors WHERE hospital_id = ? AND department_id = ? AND is_active = TRUE ORDER BY name",
        (hospital_id, department_id),
    ).fetchall()
    return [dict(r) for r in rows]


def find_doctor(hospital_id: int, department_id: str, doctor_id: str) -> dict | None:
    conn = get_connection()
    row = conn.execute(
        "SELECT id, name FROM doctors WHERE hospital_id = ? AND department_id = ? AND id = ?",
        (hospital_id, department_id, doctor_id),
    ).fetchone()
    return dict(row) if row else None


def create_department(hospital_id: int, name: str) -> dict:
    """id is a UUID-derived opaque string (not a slug of `name`), scoped by an
    h{hospital_id}_ prefix -- avoids both the collision risk of slugifying
    arbitrary user-entered text and the known Tier 1 limitation that
    departments.id is globally unique, not (hospital_id, id) composite-unique
    (db/schema.sql's comment on that table)."""
    department_id = f"h{hospital_id}_{uuid.uuid4().hex[:8]}"
    conn = get_connection()
    conn.execute(
        "INSERT INTO departments (id, hospital_id, name) VALUES (?, ?, ?)",
        (department_id, hospital_id, name),
    )
    conn.commit()
    return {"id": department_id, "name": name}


def create_doctor(
    hospital_id: int,
    department_id: str,
    name: str,
    specialization: str | None = None,
    qualification: str | None = None,
    years_experience: int | None = None,
    working_days: list[str] | None = None,
    working_hours: list[str] | None = None,
    slot_duration_minutes: int = 30,
    breaks: list[str] | None = None,
    max_bookings_per_slot: int = 1,
    daily_booking_limit: int | None = None,
    online_quota: int | None = None,
    walkin_quota: int | None = None,
    followup_duration_minutes: int | None = None,
    effective_from: str | None = None,
) -> dict:
    """working_days (e.g. ["Mon", "Wed", "Fri"]) and working_hours (e.g.
    ["10:00-13:00", "17:00-20:00"]) are this doctor's working pattern (Section
    12.1 Step 7) -- generate_slots_for_doctor() is called immediately below to
    produce the initial rolling window of real doctor_slots rows from it
    (Section 12.1.1), so onboarding a doctor through this function is what
    "run slot generation at onboarding submission time" means in practice. A
    doctor with no working_days/working_hours simply generates zero slots.

    breaks (Section 14.7, e.g. ["11:20-11:40"]) is comma-stored exactly like
    working_hours, and applies the same way -- uniformly across every working
    day, not per-specific-day. effective_from has no effect on a brand-new
    doctor (nothing to preserve yet) -- it only matters on update_doctor()."""
    doctor_id = f"h{hospital_id}_{uuid.uuid4().hex[:8]}"
    conn = get_connection()
    conn.execute(
        "INSERT INTO doctors (id, hospital_id, department_id, name, specialization, qualification, "
        "years_experience, working_days, working_hours, slot_duration_minutes, breaks, "
        "max_bookings_per_slot, daily_booking_limit, online_quota, walkin_quota, "
        "followup_duration_minutes, effective_from) "
        "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        (doctor_id, hospital_id, department_id, name, specialization, qualification,
         years_experience, ",".join(working_days or []), ",".join(working_hours or []), slot_duration_minutes,
         ",".join(breaks or []), max_bookings_per_slot, daily_booking_limit, online_quota, walkin_quota,
         followup_duration_minutes, effective_from),
    )
    conn.commit()
    generate_slots_for_doctor(hospital_id, doctor_id, conn=conn)
    return {"id": doctor_id, "name": name}


_DOCTOR_FULL_COLUMNS = (
    "id, department_id, name, specialization, qualification, years_experience, "
    "working_days, working_hours, slot_duration_minutes, breaks, max_bookings_per_slot, "
    "daily_booking_limit, online_quota, walkin_quota, followup_duration_minutes, effective_from, is_active"
)


def get_doctor_full(hospital_id: int, doctor_id: str) -> dict | None:
    """Every column, not just {id, name} like get_doctors()/find_doctor() --
    portal.py's doctor-edit form (Section 12.7 follow-up: self-serve doctor
    management) needs the full working pattern to pre-fill, and needs
    department_id from the doctor_id alone (the edit URL only carries the
    doctor's id, not which department it's under)."""
    conn = get_connection()
    row = conn.execute(
        f"SELECT {_DOCTOR_FULL_COLUMNS} FROM doctors WHERE hospital_id = ? AND id = ?",
        (hospital_id, doctor_id),
    ).fetchone()
    if row is None:
        return None
    return _parse_doctor_row(dict(row))


def _parse_doctor_row(d: dict) -> dict:
    d["working_days"] = [x for x in d["working_days"].split(",") if x]
    d["working_hours"] = [x for x in d["working_hours"].split(",") if x]
    d["breaks"] = [x for x in (d.get("breaks") or "").split(",") if x]
    return d


def get_all_doctors_for_hospital(hospital_id: int) -> list[dict]:
    """Every doctor at this hospital with its department name attached --
    portal.py's doctors list page (Section 12.7 follow-up), one query instead
    of walking get_departments() -> get_doctors() per department. Deliberately
    NOT filtered by is_active -- this is the management view, so an inactive
    doctor must still show up (with its off state) so staff can toggle it
    back on; get_doctors() is the one that hides them from bookable lists."""
    conn = get_connection()
    rows = conn.execute(
        "SELECT doc.id, doc.department_id, d.name AS department_name, doc.name, doc.specialization, doc.is_active "
        "FROM doctors doc JOIN departments d ON d.id = doc.department_id "
        "WHERE doc.hospital_id = ? ORDER BY d.name, doc.name",
        (hospital_id,),
    ).fetchall()
    return [dict(r) for r in rows]


def set_doctor_active(hospital_id: int, doctor_id: str, is_active: bool) -> bool:
    """Staff-facing on/off switch (distinct from doctor_leave's whole-day
    dates and from editing working hours) -- returns False if no matching
    doctor row exists for this hospital, True on a real update, so callers
    can 404 rather than silently no-op."""
    conn = get_connection()
    cur = conn.execute(
        "UPDATE doctors SET is_active = ? WHERE hospital_id = ? AND id = ?",
        (is_active, hospital_id, doctor_id),
    )
    conn.commit()
    return cur.rowcount > 0


def update_doctor(
    hospital_id: int,
    doctor_id: str,
    name: str,
    specialization: str | None = None,
    qualification: str | None = None,
    years_experience: int | None = None,
    working_days: list[str] | None = None,
    working_hours: list[str] | None = None,
    slot_duration_minutes: int = 30,
    breaks: list[str] | None = None,
    max_bookings_per_slot: int = 1,
    daily_booking_limit: int | None = None,
    online_quota: int | None = None,
    walkin_quota: int | None = None,
    followup_duration_minutes: int | None = None,
    effective_from: str | None = None,
) -> dict | None:
    """portal.py's doctor-edit form. Returns None if no such doctor exists at
    this hospital (nothing updated), same "hospital_id in the WHERE clause is
    the actual guard, not application logic" discipline as every other
    hospital-scoped write here.

    Regenerates doctor_slots against the (possibly changed) working pattern,
    rather than trying to reconcile old vs. new slots row by row -- safe to do
    because doctor_slots carries no foreign key from appointments (get_slots()
    matches them only by scheduled_at string equality, see that function's
    docstring), so dropping and rebuilding a doctor's still-just-offered slots
    never touches an appointment a patient has already booked.

    Section 14.7: if effective_from is set, regeneration only touches slots
    dated on/after it -- any earlier still-unbooked slots (generated under
    this doctor's PREVIOUS pattern) are left exactly as they were, so a
    schedule change that's meant to start next month doesn't retroactively
    rewrite next week's already-offered slots. effective_from=None (the
    default, matching every doctor before this column existed) wipes and
    regenerates the whole window, same as before this change."""
    conn = get_connection()
    cur = conn.execute(
        "UPDATE doctors SET name = ?, specialization = ?, qualification = ?, years_experience = ?, "
        "working_days = ?, working_hours = ?, slot_duration_minutes = ?, breaks = ?, "
        "max_bookings_per_slot = ?, daily_booking_limit = ?, online_quota = ?, walkin_quota = ?, "
        "followup_duration_minutes = ?, effective_from = ? WHERE hospital_id = ? AND id = ?",
        (name, specialization, qualification, years_experience,
         ",".join(working_days or []), ",".join(working_hours or []), slot_duration_minutes,
         ",".join(breaks or []), max_bookings_per_slot, daily_booking_limit, online_quota, walkin_quota,
         followup_duration_minutes, effective_from,
         hospital_id, doctor_id),
    )
    if cur.rowcount == 0:
        return None
    if effective_from:
        conn.execute(
            "DELETE FROM doctor_slots WHERE hospital_id = ? AND doctor_id = ? AND scheduled_at >= ?",
            (hospital_id, doctor_id, effective_from),
        )
    else:
        conn.execute("DELETE FROM doctor_slots WHERE hospital_id = ? AND doctor_id = ?", (hospital_id, doctor_id))
    conn.commit()
    generate_slots_for_doctor(hospital_id, doctor_id, conn=conn)
    return {"id": doctor_id, "name": name}


def list_doctor_ids(hospital_id: int) -> list[str]:
    """Used by the slot top-up job (slots/scheduler.py) to loop every doctor
    at a hospital without needing to walk departments first."""
    conn = get_connection()
    rows = conn.execute("SELECT id FROM doctors WHERE hospital_id = ?", (hospital_id,)).fetchall()
    return [r["id"] for r in rows]


def _parse_time_range(time_range: str) -> tuple[str, str]:
    start, end = time_range.split("-")
    return start.strip(), end.strip()


def _overlaps_break(slot_start: datetime, slot_end: datetime, breaks: list[tuple[str, str]], day: date) -> bool:
    for break_start_str, break_end_str in breaks:
        break_start = datetime.combine(day, datetime.strptime(break_start_str, "%H:%M").time())
        break_end = datetime.combine(day, datetime.strptime(break_end_str, "%H:%M").time())
        if break_start < slot_end and break_end > slot_start:
            return True
    return False


def generate_slots_for_doctor(
    hospital_id: int,
    doctor_id: str,
    days_ahead: int = _SLOT_DAYS_AHEAD,
    now: date | None = None,
    conn=None,
) -> int:
    """Generates real doctor_slots rows for the next `days_ahead` days (Section
    12.1.1) from this doctor's stored working_days/working_hours/
    slot_duration_minutes. ON CONFLICT DO NOTHING against doctor_slots' UNIQUE
    (doctor_id, scheduled_at) (db/schema.sql) is what makes this idempotent --
    calling it again for a window that's already partly populated (the
    periodic top-up job, slots/scheduler.py) only adds the new days, never
    duplicates existing ones. Returns the number of *new* slot rows inserted.

    Section 14.7 additions, all read from the same doctor row:
    - breaks: any candidate slot overlapping a break window (see
      _overlaps_break()) on that day is skipped entirely -- breaks apply
      uniformly to every working day, not a specific one (db/schema.sql's
      comment on doctors.breaks explains why).
    - doctor_leave: any date present there for this doctor is skipped
      entirely, no slots generated for it at all.
    - daily_booking_limit: once a given date would have this many candidate
      slots, generation stops for THAT date (soonest-in-the-day slots first,
      since candidates are already built in ascending time order) -- doesn't
      affect other dates.
    - effective_from: dates before it are skipped -- update_doctor() only
      deletes existing slots on/after this date (see its own docstring), so
      generating for earlier dates here would incorrectly add new-pattern
      slots alongside still-standing old-pattern ones.

    conn is an optional explicit connection (rather than get_connection())
    because db/seed.py calls this against a connection it's still assembling,
    before db.connection's shared connection has been repointed to it."""
    conn = conn or get_connection()
    doctor_row = conn.execute(
        "SELECT working_days, working_hours, slot_duration_minutes, breaks, daily_booking_limit, effective_from "
        "FROM doctors WHERE hospital_id = ? AND id = ?",
        (hospital_id, doctor_id),
    ).fetchone()
    if doctor_row is None:
        return 0

    working_days = {d.strip() for d in doctor_row["working_days"].split(",") if d.strip()}
    working_hours = [h.strip() for h in doctor_row["working_hours"].split(",") if h.strip()]
    slot_duration = doctor_row["slot_duration_minutes"]
    if not working_days or not working_hours or not slot_duration:
        return 0

    breaks = [_parse_time_range(b) for b in doctor_row["breaks"].split(",") if b.strip()] if doctor_row["breaks"] else []
    daily_booking_limit = doctor_row["daily_booking_limit"]
    effective_from = date.fromisoformat(doctor_row["effective_from"]) if doctor_row["effective_from"] else None

    today = now or date.today()
    leave_dates = {
        row["date"] for row in
        conn.execute("SELECT date FROM doctor_leave WHERE hospital_id = ? AND doctor_id = ?", (hospital_id, doctor_id)).fetchall()
    }

    candidates: list[tuple] = []
    for i in range(1, days_ahead + 1):
        d = today + timedelta(days=i)
        if _WEEKDAY_ABBREVS[d.weekday()] not in working_days:
            continue
        if effective_from and d < effective_from:
            continue
        if d.isoformat() in leave_dates:
            continue
        day_count = 0
        for time_range in working_hours:
            start_str, end_str = _parse_time_range(time_range)
            current = datetime.combine(d, datetime.strptime(start_str, "%H:%M").time())
            end = datetime.combine(d, datetime.strptime(end_str, "%H:%M").time())
            step = timedelta(minutes=slot_duration)
            while current + step <= end:
                if daily_booking_limit is not None and day_count >= daily_booking_limit:
                    break
                if not _overlaps_break(current, current + step, breaks, d):
                    candidates.append((hospital_id, doctor_id, current.isoformat()))
                    day_count += 1
                current += step

    if not candidates:
        return 0

    # One multi-row INSERT instead of one round-trip per slot -- this used to
    # be a per-slot conn.execute() in a loop, which against a real (non-local)
    # Postgres like Neon meant one network round-trip per slot: a doctor with
    # even a single ordinary shift over a 14-day window is 100+ slots, so
    # onboarding a hospital with a few doctors could take tens of seconds just
    # here. Building one INSERT with all rows' worth of "(?, ?, ?)" placeholders
    # (well within Postgres's ~65535 parameter limit for any realistic doctor
    # count/window) turns that into a single round-trip per doctor.
    placeholders = ", ".join(["(?, ?, ?)"] * len(candidates))
    flat_params = [value for row in candidates for value in row]
    cur = conn.execute(
        f"INSERT INTO doctor_slots (hospital_id, doctor_id, scheduled_at) VALUES {placeholders} "
        "ON CONFLICT (doctor_id, scheduled_at) DO NOTHING",
        flat_params,
    )
    inserted = cur.rowcount
    conn.commit()
    return inserted


# --- Doctor leave (Section 14.7 -- whole-day unavailability) ---

def get_doctor_leave(hospital_id: int, doctor_id: str) -> list[dict]:
    conn = get_connection()
    rows = conn.execute(
        "SELECT id, date, reason FROM doctor_leave WHERE hospital_id = ? AND doctor_id = ? ORDER BY date",
        (hospital_id, doctor_id),
    ).fetchall()
    return [dict(r) for r in rows]


def create_doctor_leave(hospital_id: int, doctor_id: str, leave_date: str, reason: str | None = None) -> dict:
    """leave_date is an ISO 'YYYY-MM-DD' string, matching doctor_slots'/
    appointments' own "store dates/datetimes as ISO text" convention.
    UNIQUE(doctor_id, date) (db/schema.sql) makes re-adding the same date
    harmless -- ON CONFLICT DO NOTHING rather than erroring, since a staff
    member re-submitting a date they already marked isn't a real problem.
    Regenerates this doctor's slots immediately so the new leave date takes
    effect right away, not just on the next periodic top-up."""
    conn = get_connection()
    conn.execute(
        "INSERT INTO doctor_leave (hospital_id, doctor_id, date, reason) VALUES (?, ?, ?, ?) "
        "ON CONFLICT (doctor_id, date) DO NOTHING",
        (hospital_id, doctor_id, leave_date, reason),
    )
    conn.execute("DELETE FROM doctor_slots WHERE hospital_id = ? AND doctor_id = ? AND scheduled_at >= ?",
                 (hospital_id, doctor_id, leave_date))
    conn.commit()
    generate_slots_for_doctor(hospital_id, doctor_id, conn=conn)
    return {"date": leave_date, "reason": reason}


def delete_doctor_leave(hospital_id: int, doctor_id: str, leave_id: int) -> bool:
    """Returns False if no such leave row exists for this doctor/hospital
    (nothing deleted) -- same hospital_id-scoped-guard discipline as every
    other write here. Regenerates slots so the now-freed date becomes
    bookable again immediately."""
    conn = get_connection()
    cur = conn.execute(
        "DELETE FROM doctor_leave WHERE id = ? AND hospital_id = ? AND doctor_id = ?",
        (leave_id, hospital_id, doctor_id),
    )
    if cur.rowcount == 0:
        return False
    conn.commit()
    generate_slots_for_doctor(hospital_id, doctor_id, conn=conn)
    return True


# --- Slots (real, persisted rows — see module docstring) ---

def get_slots(hospital_id: int, doctor_id: str) -> list[dict]:
    """This doctor's generated doctor_slots rows, minus any that have already
    reached this doctor's max_bookings_per_slot worth of *booked* appointments
    at that exact time (Phase 8, extended by Section 14.7: the default
    max_bookings_per_slot=1 means "any booked appointment at all," exactly
    Phase 8's original behavior; >1 keeps offering the slot until that many
    patients have booked it)."""
    conn = get_connection()
    doctor_row = conn.execute(
        "SELECT max_bookings_per_slot FROM doctors WHERE hospital_id = ? AND id = ?",
        (hospital_id, doctor_id),
    ).fetchone()
    max_bookings_per_slot = doctor_row["max_bookings_per_slot"] if doctor_row else 1

    booked_rows = conn.execute(
        "SELECT scheduled_at FROM appointments WHERE hospital_id = ? AND doctor_id = ? AND status = ?",
        (hospital_id, doctor_id, STATUS_BOOKED),
    ).fetchall()
    booked_counts: dict[str, int] = {}
    for row in booked_rows:
        booked_counts[row["scheduled_at"]] = booked_counts.get(row["scheduled_at"], 0) + 1

    slot_rows = conn.execute(
        "SELECT scheduled_at FROM doctor_slots WHERE hospital_id = ? AND doctor_id = ? ORDER BY scheduled_at",
        (hospital_id, doctor_id),
    ).fetchall()

    slots = []
    for row in slot_rows:
        scheduled_at_iso = row["scheduled_at"]
        if booked_counts.get(scheduled_at_iso, 0) >= max_bookings_per_slot:
            continue
        dt = datetime.fromisoformat(scheduled_at_iso)
        slots.append({
            "id": scheduled_at_iso,
            "date": dt.date().isoformat(),
            "time": dt.strftime("%H:%M"),
            "label": f"{dt.strftime('%a %d %b')} {dt.strftime('%H:%M')}",
        })
    return slots


def find_slot(hospital_id: int, doctor_id: str, slot_id: str) -> dict | None:
    for s in get_slots(hospital_id, doctor_id):
        if s["id"] == slot_id:
            return s
    return None


# --- Patients (Section 12.9 -- staff-created bookings need to search by name,
# not just phone; see db/schema.sql's comment on the patients table and
# create_appointment()'s _upsert_patient() for how rows get here) ---

def is_valid_phone(phone: str | None) -> bool:
    """Deliberately permissive (SPEC Section 12.9's phone-validation follow-up)
    -- rejects only the unambiguous garbage cases (empty, whitespace-only, or
    containing no digits at all, e.g. "not-a-phone-number!!"), not a strict
    phone-number format spec: no length requirement, no country-code check,
    no separator/whitespace-shape rules. International phone formats vary too
    much to validate meaningfully without a dedicated library this project
    doesn't otherwise need -- filtering garbage, not enforcing a spec, is the
    actual goal here. Called at every point a phone number is first captured:
    core/main.py's webhook intake (WhatsApp) and portal.py's new-booking form
    (staff) -- not re-checked here in create_appointment() itself, since both
    of those are the only real entry points and re-validating a third time
    at the shared data-access layer would just be the same rule maintained
    in three places instead of two."""
    if not phone:
        return False
    phone = phone.strip()
    if not phone:
        return False
    return any(c.isdigit() for c in phone)


def search_patients(hospital_id: int, query: str, limit: int = 10) -> list[dict]:
    """Case-insensitive partial match on name OR phone, hospital-scoped.
    Powers portal.py's /portal/patients/search (staff typing into the new-
    booking form's patient search box)."""
    query = query.strip()
    if not query:
        return []
    conn = get_connection()
    like = f"%{query}%"
    rows = conn.execute(
        "SELECT phone, name FROM patients WHERE hospital_id = ? "
        "AND (phone ILIKE ? OR name ILIKE ?) ORDER BY name NULLS LAST, phone LIMIT ?",
        (hospital_id, like, like, limit),
    ).fetchall()
    return [{"phone": r["phone"], "name": r["name"]} for r in rows]


# --- Appointments ---

def _upsert_patient(conn, hospital_id: int, phone: str, name: str | None) -> None:
    """Section 12.9: keeps `patients` in sync on every booking, both sources.
    COALESCE(EXCLUDED.name, patients.name) means a name, when given (staff
    bookings), always wins and fills in/overwrites; when not given (every
    WhatsApp booking, which never collects one), an existing name is never
    clobbered back to NULL."""
    conn.execute(
        "INSERT INTO patients (hospital_id, phone, name) VALUES (?, ?, ?) "
        "ON CONFLICT (hospital_id, phone) DO UPDATE SET name = COALESCE(EXCLUDED.name, patients.name)",
        (hospital_id, phone, name),
    )


def create_appointment(
    hospital_id: int,
    phone: str,
    department_id: str,
    doctor_id: str,
    scheduled_at: datetime,
    source: str = SOURCE_WHATSAPP,
    patient_name: str | None = None,
) -> Appointment:
    """Raises db.connection.IntegrityError if this doctor's max_bookings_per_slot
    (default 1) worth of *booked* appointments already exist at this exact
    scheduled_at -- that's the actual double-booking guard, not application
    logic. Catching it gracefully is Phase 8 work, not done here. Raises the
    more specific QuotaExceededError (still an IntegrityError) if the
    doctor's daily_booking_limit or the requested source's online_quota/
    walkin_quota (Section 14.7, first enforced here as of Section 12.9) is
    exhausted for scheduled_at's date.

    `source` distinguishes a WhatsApp patient self-booking (the default --
    every pre-Section-12.9 call site keeps working completely unchanged) from
    a staff-created walk-in/phone booking ("staff", portal.py's
    /portal/new-booking) -- purely descriptive, never branched on for booking
    LOGIC beyond which quota column it counts against. `patient_name` is only
    ever supplied by the staff path (core/booking_flow.py never collects a
    patient's name); see _upsert_patient().

    Concurrency (Section 12.9): daily_booking_limit/online_quota/walkin_quota
    are per-DOCTOR-configured values, not fixed schema constants, so unlike
    the OLD max_bookings_per_slot-only design (a plain UNIQUE index needed no
    lock at all) they can't be enforced as a static constraint. A Postgres
    advisory transaction lock scoped to (doctor_id, date) serializes every
    booking attempt -- staff AND WhatsApp alike -- for the same doctor on the
    same day, so the whole check-then-insert sequence below (quotas AND the
    per-slot ordinal assignment) is atomic against genuine concurrent
    requests, not just correct when called one at a time. The lock is
    released automatically on COMMIT/ROLLBACK (that's what "_xact_lock"
    means).

    Wrapped in a real BEGIN/ROLLBACK/COMMIT block (unlike every other
    function in this file, which relies on db/connection.py's
    autocommit=True) -- the `except BaseException` below is not optional:
    this is the ONE place in the app that opens a real multi-statement
    transaction on the single shared connection, and leaving it open after an
    unexpected error would poison every subsequent query on that connection
    (db/connection.py's own docstring explains exactly this failure mode,
    which is why autocommit=True was chosen everywhere else) -- so every exit
    path, expected or not, must ROLLBACK or COMMIT. This is also exactly why
    there's deliberately no retry-on-conflict inside this transaction (an
    earlier version had one, a leftover from before this lock existed): once
    ANY statement in an explicit Postgres transaction fails, the whole
    transaction is aborted and every FURTHER statement on it fails too, with
    "current transaction is aborted" (a different exception than whatever
    actually went wrong) until a ROLLBACK -- so "catch a failure and issue
    another statement to retry, inside the same transaction" doesn't just
    not-help here, it actively replaces a meaningful IntegrityError/
    QuotaExceededError with a useless, wrong-typed one that no caller's
    `except IntegrityError:` would catch. Confirmed live: forcing a genuine
    INSERT failure here and then issuing an unrelated query on the same
    connection afterward shows the connection recovers cleanly either way
    (see tests/test_create_appointment_transaction_safety.py) -- but ONLY
    the current code (no inner retry) also gets the exception TYPE right for
    the caller."""
    conn = get_connection()
    scheduled_at_iso = scheduled_at.isoformat()
    scheduled_date = scheduled_at.date()
    day_start = datetime.combine(scheduled_date, datetime.min.time()).isoformat()
    day_end = datetime.combine(scheduled_date, datetime.max.time()).isoformat()

    doctor_row = conn.execute(
        "SELECT max_bookings_per_slot, daily_booking_limit, online_quota, walkin_quota "
        "FROM doctors WHERE hospital_id = ? AND id = ?",
        (hospital_id, doctor_id),
    ).fetchone()
    max_bookings_per_slot = doctor_row["max_bookings_per_slot"] if doctor_row else 1
    daily_booking_limit = doctor_row["daily_booking_limit"] if doctor_row else None
    source_quota = None
    if doctor_row:
        source_quota = doctor_row["online_quota"] if source == SOURCE_WHATSAPP else doctor_row["walkin_quota"]

    conn.execute("BEGIN")
    try:
        conn.execute(
            "SELECT pg_advisory_xact_lock(hashtext(?))",
            (f"{doctor_id}|{scheduled_date.isoformat()}",),
        )

        if daily_booking_limit is not None:
            day_count = conn.execute(
                "SELECT COUNT(*) AS c FROM appointments WHERE hospital_id = ? AND doctor_id = ? "
                "AND scheduled_at >= ? AND scheduled_at <= ? AND status = ?",
                (hospital_id, doctor_id, day_start, day_end, STATUS_BOOKED),
            ).fetchone()["c"]
            if day_count >= daily_booking_limit:
                raise QuotaExceededError("This doctor has reached today's booking limit.")

        if source_quota is not None:
            source_count = conn.execute(
                "SELECT COUNT(*) AS c FROM appointments WHERE hospital_id = ? AND doctor_id = ? "
                "AND scheduled_at >= ? AND scheduled_at <= ? AND status = ? AND source = ?",
                (hospital_id, doctor_id, day_start, day_end, STATUS_BOOKED, source),
            ).fetchone()["c"]
            if source_count >= source_quota:
                kind = "Online booking" if source == SOURCE_WHATSAPP else "Walk-in"
                raise QuotaExceededError(f"{kind} quota full for this doctor today.")

        # The smallest booking_ordinal in [0, max_bookings_per_slot) NOT
        # already used by a currently-BOOKED row at this exact slot --
        # deliberately NOT a plain COUNT(*): a cancellation doesn't delete
        # its row or free its ordinal implicitly, so booked ordinals can have
        # gaps (book A -> ordinal 0, book B -> ordinal 1, cancel A, book C ->
        # COUNT(booked) is 1, but ordinal 1 is already B's -- COUNT(*) as the
        # ordinal would collide with B here, a real sequence, not a
        # contrived one). generate_series against the valid ordinal range,
        # minus whichever are taken, correctly finds a real gap or reports
        # none exists.
        free_ordinal_row = conn.execute(
            "SELECT MIN(o) AS ordinal FROM generate_series(0, ? - 1) AS o "
            "WHERE o NOT IN (SELECT booking_ordinal FROM appointments WHERE hospital_id = ? "
            "AND doctor_id = ? AND scheduled_at = ? AND status = ?)",
            (max_bookings_per_slot, hospital_id, doctor_id, scheduled_at_iso, STATUS_BOOKED),
        ).fetchone()
        if free_ordinal_row["ordinal"] is None:
            raise IntegrityError(f"doctor {doctor_id} has no free booking slot at {scheduled_at_iso}")

        # No retry-on-conflict here (an earlier version of this function had
        # one, left over from before the advisory lock above existed): under
        # the lock, no other transaction can be concurrently computing an
        # ordinal for this doctor+day, so this INSERT cannot lose a race --
        # and critically, retrying-by-issuing-more-statements would NOT be
        # safe here even if it could theoretically happen: Postgres aborts an
        # entire explicit transaction after any failed statement, so a second
        # statement issued after a failed INSERT here would itself fail with
        # "current transaction is aborted", not this table's own
        # IntegrityError -- silently breaking every caller's
        # `except IntegrityError:` handling. Let it propagate straight to the
        # `except BaseException` below instead, which ROLLBACKs correctly and
        # re-raises the SAME, correctly-typed exception.
        cur = conn.execute(
            "INSERT INTO appointments (hospital_id, phone, department_id, doctor_id, scheduled_at, "
            "booking_ordinal, source) VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id",
            (hospital_id, phone, department_id, doctor_id, scheduled_at_iso, free_ordinal_row["ordinal"], source),
        )
        new_id = cur.fetchone()["id"]

        _upsert_patient(conn, hospital_id, phone, patient_name)
        conn.execute("COMMIT")
    except BaseException:
        try:
            conn.execute("ROLLBACK")
        except Exception:
            pass
        raise

    return get_appointment(hospital_id, new_id)


def get_appointment(hospital_id: int, appointment_id: int) -> Appointment | None:
    conn = get_connection()
    row = conn.execute(
        _APPOINTMENT_SELECT + " WHERE a.id = ? AND a.hospital_id = ?",
        (appointment_id, hospital_id),
    ).fetchone()
    return _row_to_appointment(row) if row else None


def get_upcoming_appointments_for_phone(hospital_id: int, phone: str, now: datetime | None = None) -> list[Appointment]:
    """A patient's own future, still-booked appointments — soonest first.
    Past appointments and ones already cancelled/rescheduled are excluded here
    (not filtered later) so callers never have to remember to check status."""
    now = now or datetime.now()
    conn = get_connection()
    rows = conn.execute(
        _APPOINTMENT_SELECT + " WHERE a.hospital_id = ? AND a.phone = ? AND a.status = ? AND a.scheduled_at > ? "
        "ORDER BY a.scheduled_at ASC",
        (hospital_id, phone, STATUS_BOOKED, now.isoformat()),
    ).fetchall()
    return [_row_to_appointment(r) for r in rows]


def get_upcoming_appointments(hospital_id: int, offset_hours: float, now: datetime | None = None) -> list[Appointment]:
    """Still-booked appointments scheduled between `now` and `now + offset_hours`
    that haven't had a reminder sent yet *for this specific offset* — a hospital
    can configure multiple offsets (SPEC Section 4's reminder_offsets_hours, e.g.
    24h-before AND 1h-before), each tracked independently via appointment_reminders
    so configuring more than one actually results in more than one reminder per
    appointment, rather than the first one sent silently blocking the rest.
    Used by reminders/scheduler.py, once per offset."""
    now = now or datetime.now()
    cutoff = now + timedelta(hours=offset_hours)
    conn = get_connection()
    rows = conn.execute(
        _APPOINTMENT_SELECT + """
        WHERE a.hospital_id = ? AND a.status = ?
          AND a.scheduled_at >= ? AND a.scheduled_at <= ?
          AND NOT EXISTS (
              SELECT 1 FROM appointment_reminders ar
              WHERE ar.appointment_id = a.id AND ar.offset_hours = ?
          )
        ORDER BY a.scheduled_at ASC
        """,
        (hospital_id, STATUS_BOOKED, now.isoformat(), cutoff.isoformat(), offset_hours),
    ).fetchall()
    return [_row_to_appointment(r) for r in rows]


def get_all_appointments_for_hospital(hospital_id: int, limit: int = 500) -> list[Appointment]:
    """Every appointment (any status) for a hospital's own bookings dashboard
    (portal.py, Tier 1 self-serve view) -- most recently scheduled first.
    Unlike get_upcoming_appointments_for_phone()/get_upcoming_appointments(),
    this is intentionally not filtered to booked/future-only: hospital staff
    reviewing their own bookings want to see cancellations/reschedules too."""
    conn = get_connection()
    rows = conn.execute(
        _APPOINTMENT_SELECT + " WHERE a.hospital_id = ? ORDER BY a.scheduled_at DESC LIMIT ?",
        (hospital_id, limit),
    ).fetchall()
    return [_row_to_appointment(r) for r in rows]


def mark_reminded(hospital_id: int, appointment_id: int, offset_hours: float) -> None:
    """Records that the reminder for this specific offset has been sent.
    ON CONFLICT DO NOTHING + appointment_reminders' UNIQUE(appointment_id, offset_hours)
    (db/schema.sql) means calling this twice for the same offset is a safe no-op,
    not a duplicate record — that constraint is the actual no-double-send
    guarantee, same pattern as the double-booking index from Phase 8."""
    conn = get_connection()
    conn.execute(
        "INSERT INTO appointment_reminders (hospital_id, appointment_id, offset_hours) VALUES (?, ?, ?) "
        "ON CONFLICT (appointment_id, offset_hours) DO NOTHING",
        (hospital_id, appointment_id, offset_hours),
    )
    conn.commit()


def get_reminded_offsets(hospital_id: int, appointment_id: int) -> list[float]:
    """Which reminder offsets (in hours) have already fired for this appointment."""
    conn = get_connection()
    rows = conn.execute(
        "SELECT offset_hours FROM appointment_reminders WHERE hospital_id = ? AND appointment_id = ? ORDER BY offset_hours DESC",
        (hospital_id, appointment_id),
    ).fetchall()
    return [r["offset_hours"] for r in rows]


def cancel_appointment(hospital_id: int, appointment_id: int) -> None:
    """Marks the appointment cancelled — does not delete the row, so
    cancellation history/audit trail isn't lost. Also stamps updated_at
    (Section 12.8) so the dashboard's activity feed can show this event at
    the time it actually happened, not the original booking's created_at."""
    conn = get_connection()
    conn.execute(
        "UPDATE appointments SET status = ?, updated_at = ? WHERE id = ? AND hospital_id = ?",
        (STATUS_CANCELLED, datetime.now().isoformat(), appointment_id, hospital_id),
    )
    conn.commit()


def mark_rescheduled(hospital_id: int, appointment_id: int) -> None:
    """Marks the old appointment as superseded by a reschedule — does not
    delete the row. Callers are responsible for create_appointment()-ing the
    new slot separately (see core/booking_flow.py's reschedule confirm).
    Also stamps updated_at (Section 12.8), same reasoning as cancel_appointment()."""
    conn = get_connection()
    conn.execute(
        "UPDATE appointments SET status = ?, updated_at = ? WHERE id = ? AND hospital_id = ?",
        (STATUS_RESCHEDULED, datetime.now().isoformat(), appointment_id, hospital_id),
    )
    conn.commit()


# --- Staff dashboard (SPEC Section 12.8) -- portal.py's /portal/dashboard.
# Every query here is hospital_id-scoped, same discipline as everywhere else
# in this file; the isolation test that matters is at the HTTP layer
# (tests/test_portal_dashboard.py), not repeated per-function here. ---

def get_dashboard_stats(hospital_id: int, now: datetime | None = None) -> dict:
    """The four stat tiles (today's appointments, confirmed today, new
    patients today, no-shows today) plus a week-over-week % change for each,
    comparing today against the SAME WEEKDAY exactly 7 days ago -- picked
    over a rolling-7-day-average comparison because it's the simplest
    comparison that's still apples-to-apples (a Monday against last Monday,
    not "today" against a blended mix of arbitrary weekdays), and needs only
    a single extra date offset, not a second aggregate shape.

    Definitions (all hospital_id + date-scoped):
    - "today's appointments": every appointment (any status) with
      scheduled_at falling on the date in question.
    - "confirmed today": of those, the ones still status='booked' (i.e. not
      cancelled) -- "confirmed" reads most naturally as "still on," not "has
      been formally re-confirmed" (no such action exists in this app).
    - "new patients today": distinct phone numbers whose EARLIEST appointment
      ever at this hospital (by created_at) was created on the date in
      question -- there's no separate patients table, so "new" is derived
      from first-appearance-in-appointments.
    - "no-shows today": still status='booked' appointments whose scheduled_at
      has already passed as of `now` (or, for last week's comparison day,
      the whole day, since it's entirely in the past). KNOWN LIMITATION: this
      app has no "attended"/"completed" status, so this is a heuristic, not a
      true no-show flag -- a booked appointment the patient actually attended
      looks identical to one they skipped once its time has passed. Flagged
      here deliberately rather than silently treated as exact.

    A week-over-week % change with a zero baseline (nothing happened on the
    comparison day) returns None (not a divide-by-zero, not a misleading
    "+100%") -- the caller/template shows "—" for that case.
    """
    now = now or datetime.now()
    today = now.date()
    last_week_day = today - timedelta(days=7)
    conn = get_connection()

    def _stats_for_day(day, no_show_cutoff: datetime) -> dict:
        day_start = datetime.combine(day, datetime.min.time()).isoformat()
        day_end = datetime.combine(day, datetime.max.time()).isoformat()
        total = conn.execute(
            "SELECT COUNT(*) AS c FROM appointments WHERE hospital_id = ? AND scheduled_at >= ? AND scheduled_at <= ?",
            (hospital_id, day_start, day_end),
        ).fetchone()["c"]
        confirmed = conn.execute(
            "SELECT COUNT(*) AS c FROM appointments WHERE hospital_id = ? AND scheduled_at >= ? AND scheduled_at <= ? AND status = ?",
            (hospital_id, day_start, day_end, STATUS_BOOKED),
        ).fetchone()["c"]
        new_patients = conn.execute(
            "SELECT COUNT(DISTINCT a.phone) AS c FROM appointments a "
            "WHERE a.hospital_id = ? AND a.created_at >= ? AND a.created_at <= ? "
            "AND NOT EXISTS (SELECT 1 FROM appointments a2 WHERE a2.hospital_id = a.hospital_id "
            "AND a2.phone = a.phone AND a2.created_at < ?)",
            (hospital_id, day_start, day_end, day_start),
        ).fetchone()["c"]
        no_shows = conn.execute(
            "SELECT COUNT(*) AS c FROM appointments WHERE hospital_id = ? AND scheduled_at >= ? AND scheduled_at <= ? "
            "AND scheduled_at < ? AND status = ?",
            (hospital_id, day_start, day_end, no_show_cutoff.isoformat(), STATUS_BOOKED),
        ).fetchone()["c"]
        return {"total": total, "confirmed": confirmed, "new_patients": new_patients, "no_shows": no_shows}

    today_stats = _stats_for_day(today, now)
    last_week_stats = _stats_for_day(last_week_day, datetime.combine(last_week_day, datetime.max.time()))

    def _delta_pct(today_v: int, last_week_v: int) -> float | None:
        if last_week_v == 0:
            return None
        return round((today_v - last_week_v) / last_week_v * 100, 1)

    return {
        "today_appointments": today_stats["total"],
        "today_appointments_delta_pct": _delta_pct(today_stats["total"], last_week_stats["total"]),
        "confirmed_today": today_stats["confirmed"],
        "confirmed_today_delta_pct": _delta_pct(today_stats["confirmed"], last_week_stats["confirmed"]),
        "new_patients_today": today_stats["new_patients"],
        "new_patients_today_delta_pct": _delta_pct(today_stats["new_patients"], last_week_stats["new_patients"]),
        "no_shows_today": today_stats["no_shows"],
        "no_shows_today_delta_pct": _delta_pct(today_stats["no_shows"], last_week_stats["no_shows"]),
    }


def get_weekly_appointment_counts(hospital_id: int, now: datetime | None = None) -> list[dict]:
    """One point per day for the last 7 calendar days (today inclusive,
    oldest first) -- counts by scheduled_at (any status), consistent with
    get_dashboard_stats()'s own "today's appointments" definition (appointment
    VOLUME by day), not by created_at (which would be a booking-activity
    trend instead -- a legitimate alternative, but this keeps every dashboard
    number reading the same way)."""
    now = now or datetime.now()
    today = now.date()
    conn = get_connection()
    results = []
    for i in range(6, -1, -1):
        day = today - timedelta(days=i)
        day_start = datetime.combine(day, datetime.min.time()).isoformat()
        day_end = datetime.combine(day, datetime.max.time()).isoformat()
        count = conn.execute(
            "SELECT COUNT(*) AS c FROM appointments WHERE hospital_id = ? AND scheduled_at >= ? AND scheduled_at <= ?",
            (hospital_id, day_start, day_end),
        ).fetchone()["c"]
        results.append({"date": day.isoformat(), "label": day.strftime("%a"), "count": count})
    return results


def get_appointments_by_department(hospital_id: int, days: int = 30, now: datetime | None = None) -> list[dict]:
    """Department share of appointment volume over a rolling `days`-day
    window ending now (default last 30 days, inclusive of today) -- ordered
    by count descending so the donut/legend both read largest-share-first."""
    now = now or datetime.now()
    window_start = datetime.combine(now.date() - timedelta(days=days - 1), datetime.min.time())
    conn = get_connection()
    rows = conn.execute(
        "SELECT d.name AS department_name, COUNT(*) AS c FROM appointments a "
        "JOIN departments d ON d.id = a.department_id "
        "WHERE a.hospital_id = ? AND a.scheduled_at >= ? AND a.scheduled_at <= ? "
        "GROUP BY d.name ORDER BY c DESC",
        (hospital_id, window_start.isoformat(), now.isoformat()),
    ).fetchall()
    return [{"department_name": r["department_name"], "count": r["c"]} for r in rows]


def get_recent_activity_feed(hospital_id: int, limit: int = 10) -> list[dict]:
    """A lightweight "what just happened" feed built entirely from
    appointments' own status/timestamps -- SPEC Section 12.8 looked for an
    existing WhatsApp message log to reuse and found none exists (nothing in
    this build persists inbound/outbound message text, only conversation
    STATE via core/history.py's session store); appointment status changes
    are the smallest real substitute already captured, so this reuses those
    rather than adding new message logging.

    Each row contributes exactly ONE event based on its CURRENT status: a
    still-'booked' row's event is "Booked appointment" at created_at; a
    cancelled/rescheduled row's event uses updated_at (the column
    cancel_appointment()/mark_rescheduled() now stamp specifically for this)
    so it shows the time the status actually changed, not the original
    booking time. A reschedule legitimately produces two feed entries over
    time -- the OLD row's "Rescheduled appointment" and the NEW row's own
    later "Booked appointment" -- which is correct, not a double-count: two
    real, separately-timed things happened."""
    conn = get_connection()
    rows = conn.execute(
        """
        SELECT a.status, a.phone, doc.name AS doctor_name, d.name AS department_name,
               a.created_at, a.updated_at
        FROM appointments a
        JOIN departments d ON d.id = a.department_id
        JOIN doctors doc ON doc.id = a.doctor_id
        WHERE a.hospital_id = ?
        ORDER BY COALESCE(a.updated_at, a.created_at) DESC
        LIMIT ?
        """,
        (hospital_id, limit),
    ).fetchall()
    labels = {
        STATUS_BOOKED: "Booked appointment",
        STATUS_CANCELLED: "Cancelled appointment",
        STATUS_RESCHEDULED: "Rescheduled appointment",
    }
    feed = []
    for r in rows:
        event_at = r["updated_at"] or r["created_at"]
        feed.append({
            "label": labels.get(r["status"], r["status"]),
            "phone": r["phone"],
            "doctor_name": r["doctor_name"],
            "department_name": r["department_name"],
            "at": datetime.fromisoformat(event_at),
        })
    return feed


# --- FAQ topics (SPEC Section 14.2, the FAQ flow_type's entire data model) ---

def get_faq_topics(hospital_id: int) -> list[dict]:
    """faq_flow.py's topic menu (Section 14.2) -- ordered by display_order,
    then id as a tiebreaker (display_order isn't unique, ties are expected)."""
    conn = get_connection()
    rows = conn.execute(
        "SELECT id, topic_label, answer_text, display_order FROM faq_topics "
        "WHERE hospital_id = ? ORDER BY display_order, id",
        (hospital_id,),
    ).fetchall()
    return [dict(r) for r in rows]


def find_faq_topic(hospital_id: int, topic_id: str) -> dict | None:
    """topic_id arrives as a WhatsApp interactive-reply id (always a string)
    -- faq_topics.id is a SERIAL int, so a non-numeric/stale/cross-hospital id
    (e.g. a leftover tap from before a flow_type switch) safely resolves to
    "not found" rather than a raw ValueError from the int() conversion."""
    try:
        topic_id_int = int(topic_id)
    except (TypeError, ValueError):
        return None
    conn = get_connection()
    row = conn.execute(
        "SELECT id, topic_label, answer_text, display_order FROM faq_topics "
        "WHERE hospital_id = ? AND id = ?",
        (hospital_id, topic_id_int),
    ).fetchone()
    return dict(row) if row else None


def create_faq_topic(
    hospital_id: int, topic_label: str, answer_text: str, display_order: int | None = None,
) -> dict:
    """admin/onboarding.py's wizard Step 7 topic/answer builder (Section 14.3,
    faq-flow tenants only). display_order defaults to "append at the end" of
    this hospital's existing topics, so onboarding-time topics keep the order
    they were entered in without the caller having to compute indices itself."""
    conn = get_connection()
    if display_order is None:
        row = conn.execute(
            "SELECT COALESCE(MAX(display_order), -1) + 1 AS next_order FROM faq_topics WHERE hospital_id = ?",
            (hospital_id,),
        ).fetchone()
        display_order = row["next_order"]
    cur = conn.execute(
        "INSERT INTO faq_topics (hospital_id, topic_label, answer_text, display_order) "
        "VALUES (?, ?, ?, ?) RETURNING id",
        (hospital_id, topic_label, answer_text, display_order),
    )
    new_id = cur.fetchone()["id"]
    conn.commit()
    return {"id": new_id, "topic_label": topic_label, "answer_text": answer_text, "display_order": display_order}


# --- Human handoff queue -- fed by flows.py's reception_handoff feature and
# core/main.py's unexpected-exception catch (see db/schema.sql's own comment
# on handoff_requests for why these two unrelated triggers share one table). ---

def create_handoff_request(hospital_id: int, phone: str, reason: str, message_text: str | None = None) -> dict:
    conn = get_connection()
    cur = conn.execute(
        "INSERT INTO handoff_requests (hospital_id, phone, reason, message_text) "
        "VALUES (?, ?, ?, ?) RETURNING id, created_at",
        (hospital_id, phone, reason, message_text),
    )
    row = cur.fetchone()
    conn.commit()
    return {
        "id": row["id"], "hospital_id": hospital_id, "phone": phone, "reason": reason,
        "message_text": message_text, "status": "open", "created_at": row["created_at"], "resolved_at": None,
    }


def get_handoff_requests(hospital_id: int, status: str | None = "open", limit: int = 100) -> list[dict]:
    """status=None returns every request regardless of state (for a staff
    member reviewing history); the default "open" is the actual work queue."""
    conn = get_connection()
    if status is None:
        rows = conn.execute(
            "SELECT id, phone, reason, message_text, status, created_at, resolved_at FROM handoff_requests "
            "WHERE hospital_id = ? ORDER BY created_at DESC LIMIT ?",
            (hospital_id, limit),
        ).fetchall()
    else:
        rows = conn.execute(
            "SELECT id, phone, reason, message_text, status, created_at, resolved_at FROM handoff_requests "
            "WHERE hospital_id = ? AND status = ? ORDER BY created_at DESC LIMIT ?",
            (hospital_id, status, limit),
        ).fetchall()
    return [dict(r) for r in rows]


def resolve_handoff_request(hospital_id: int, handoff_id: int) -> bool:
    conn = get_connection()
    cur = conn.execute(
        "UPDATE handoff_requests SET status = 'resolved', resolved_at = ? WHERE id = ? AND hospital_id = ? AND status = 'open'",
        (datetime.now().isoformat(), handoff_id, hospital_id),
    )
    conn.commit()
    return cur.rowcount > 0
