# db/repository.py
"""
The single data-access surface core/booking_flow.py and reminders/scheduler.py
talk to (SPEC Section 12.6 Tier 1) — no raw SQL anywhere outside this file.
Every function that reads/writes hospital-scoped data takes hospital_id and
filters by it (SPEC Section 12.2: "no query should ever return or write data
without this filter").

get_slots()/find_slot() read real, persisted rows from doctor_slots (Section
12.1.1) generated by generate_slots_for_doctor() from each doctor's working
pattern (working_days/working_hours/slot_duration_minutes) — no more
synthetic/computed-on-the-fly slots. As of Phase 8 they still exclude slots
that already have a *booked* appointment, so an already-taken slot is never
re-offered to another patient.
"""
import hashlib
import hmac
import json as json_lib
import os
import uuid
from dataclasses import dataclass
from datetime import date, datetime, timedelta

from db.connection import get_connection

STATUS_BOOKED = "booked"
STATUS_CANCELLED = "cancelled"
STATUS_RESCHEDULED = "rescheduled"

_SLOT_DAYS_AHEAD = 14

_WEEKDAY_ABBREVS = ("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")

_APPOINTMENT_SELECT = """
    SELECT a.id, a.hospital_id, a.phone, a.department_id, d.name AS department_name,
           a.doctor_id, doc.name AS doctor_name, a.scheduled_at, a.status
    FROM appointments a
    JOIN departments d ON d.id = a.department_id
    JOIN doctors doc ON doc.id = a.doctor_id
"""


@dataclass
class Appointment:
    id: int
    hospital_id: int
    phone: str
    department_id: str
    department_name: str
    doctor_id: str
    doctor_name: str
    scheduled_at: datetime
    status: str = STATUS_BOOKED


def _row_to_appointment(row) -> Appointment:
    return Appointment(
        id=row["id"],
        hospital_id=row["hospital_id"],
        phone=row["phone"],
        department_id=row["department_id"],
        department_name=row["department_name"],
        doctor_id=row["doctor_id"],
        doctor_name=row["doctor_name"],
        scheduled_at=datetime.fromisoformat(row["scheduled_at"]),
        status=row["status"],
    )


# --- Hospitals (SPEC Section 12.2: multi-tenant routing, Phase 9) ---

_PBKDF2_ITERATIONS = 100_000


def hash_portal_password(password: str) -> str:
    """Salted PBKDF2-SHA256, stdlib only (no new dependency for what's still a
    'basic protection, not production-grade auth' project) -- used for the
    Section 12.7 hospital-staff bookings portal login, which is stored as an
    irreversible hash (unlike access_token/app_secret, which the app must be
    able to read back to call Meta's API with -- a login password never needs
    to be reversed, only verified, so there's no reason to store it in a
    reversible form the way those are). Stored as 'salt_hex:hash_hex'."""
    salt = os.urandom(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode(), salt, _PBKDF2_ITERATIONS)
    return f"{salt.hex()}:{digest.hex()}"


def verify_portal_password(password: str, stored_hash: str) -> bool:
    try:
        salt_hex, digest_hex = stored_hash.split(":", 1)
    except (ValueError, AttributeError):
        return False
    salt = bytes.fromhex(salt_hex)
    candidate = hashlib.pbkdf2_hmac("sha256", password.encode(), salt, _PBKDF2_ITERATIONS)
    return hmac.compare_digest(candidate.hex(), digest_hex)


@dataclass
class Hospital:
    id: int
    name: str
    whatsapp_phone_number_id: str | None
    access_token: str | None  # DB column: meta_access_token_ref
    app_secret: str | None  # DB column: app_secret_ref
    timezone: str
    welcome_message_text: str | None
    reminder_offsets_hours: list[float]
    reminder_template_name: str | None
    is_active: bool
    data_tier: str
    external_api_base_url: str | None
    external_api_key: str | None
    portal_password_hash: str | None
    enabled_features: list[str]


def _row_to_hospital(row) -> Hospital:
    try:
        offsets = json_lib.loads(row["reminder_offsets_hours"])
        if not isinstance(offsets, list) or not offsets:
            raise ValueError
    except (TypeError, ValueError):
        offsets = [24]
    try:
        enabled_features = json_lib.loads(row["enabled_features"])
        if not isinstance(enabled_features, list):
            raise ValueError
    except (TypeError, ValueError):
        # NULL (not yet backfilled -- db/init_db.py's _backfill_enabled_features()
        # should have already run by the time anything queries this, but fail
        # safe to "nothing enabled" rather than crash a row read) or malformed.
        enabled_features = []
    return Hospital(
        id=row["id"],
        name=row["name"],
        whatsapp_phone_number_id=row["whatsapp_phone_number_id"],
        access_token=row["meta_access_token_ref"],
        app_secret=row["app_secret_ref"],
        timezone=row["timezone"],
        welcome_message_text=row["welcome_message_text"],
        reminder_offsets_hours=offsets,
        reminder_template_name=row["reminder_template_name"],
        is_active=bool(row["is_active"]),
        data_tier=row["data_tier"],
        external_api_base_url=row["external_api_base_url"],
        external_api_key=row["external_api_key"],
        portal_password_hash=row["portal_password_hash"],
        enabled_features=enabled_features,
    )


def find_hospital_by_phone_number_id(phone_number_id: str) -> Hospital | None:
    """The entry point for per-message multi-tenant routing (SPEC Section 12.2):
    given the phone_number_id from an incoming webhook's `metadata`, resolve which
    hospital received it. Only active hospitals are matched — a deactivated
    hospital's number should be treated the same as an unrecognized one."""
    conn = get_connection()
    row = conn.execute(
        "SELECT * FROM hospitals WHERE whatsapp_phone_number_id = ? AND is_active = 1",
        (phone_number_id,),
    ).fetchone()
    return _row_to_hospital(row) if row else None


def get_active_hospitals() -> list[Hospital]:
    """Used by reminders/scheduler.py's caller (core/main.py) to loop over every
    active hospital rather than a single startup-resolved one."""
    conn = get_connection()
    rows = conn.execute("SELECT * FROM hospitals WHERE is_active = 1 ORDER BY id").fetchall()
    return [_row_to_hospital(r) for r in rows]


def get_all_hospitals() -> list[Hospital]:
    """Every hospital regardless of is_active -- admin/onboarding.py's tenant
    list page (Section 12.1 follow-up: closing the "onboarding is self-serve,
    correcting it isn't" gap) needs to show every onboarded tenant, not just
    active ones, so there's somewhere to find a deactivated tenant's id too."""
    conn = get_connection()
    rows = conn.execute("SELECT * FROM hospitals ORDER BY id").fetchall()
    return [_row_to_hospital(r) for r in rows]


def get_hospital(hospital_id: int) -> Hospital | None:
    conn = get_connection()
    row = conn.execute("SELECT * FROM hospitals WHERE id = ?", (hospital_id,)).fetchone()
    return _row_to_hospital(row) if row else None


def find_hospital_by_portal_password(password: str) -> Hospital | None:
    """portal.py's login: which hospital does this password belong to. Each
    hash carries its own random salt (hash_portal_password()), so two
    hospitals CAN pick the identical password and still get different stored
    hashes -- there's no way to look one up by an equality WHERE clause, only
    by hashing the candidate against every stored hash and checking for a
    match. Fine at this project's scale (dozens/hundreds of hospitals, not
    millions); an actual login-throughput bottleneck would need a different
    scheme, but isn't a real concern yet."""
    for hospital in get_all_hospitals():
        if hospital.portal_password_hash and hospital.is_active:
            if verify_portal_password(password, hospital.portal_password_hash):
                return hospital
    return None


def create_hospital(
    name: str,
    whatsapp_phone_number_id: str,
    access_token: str | None = None,
    app_secret: str | None = None,
    timezone: str = "UTC",
    welcome_message_text: str | None = None,
    reminder_offsets_hours: list[float] | None = None,
    reminder_template_name: str | None = None,
    data_tier: str = "tier1",
    external_api_base_url: str | None = None,
    external_api_key: str | None = None,
    portal_password: str | None = None,
    enabled_features: list[str] | None = None,
) -> Hospital:
    """Onboarding wizard's entry point (SPEC Section 12.1, Phase 10). Raises
    db.connection.IntegrityError if whatsapp_phone_number_id is already used by
    another hospital -- db/schema.sql's UNIQUE constraint is the actual guard
    against breaking Phase 9's per-message routing, not application logic;
    callers (admin/onboarding.py) are responsible for catching it.

    data_tier (Section 12.6, Step 0 of the wizard as of Section 14.6's
    reorder): "tier1" (default, this product's own database), "tier2"
    (external_api_base_url/external_api_key are only stored here -- no
    connector logic reads them yet), or "tier3" (direct DB connection, not
    self-serve -- neither field is meaningful for it).

    portal_password (Section 12.7): plaintext in, hashed before storage --
    optional at onboarding time (a hospital can set it later via the edit
    form); left unset, the bookings portal simply has no way to log into that
    hospital yet.

    enabled_features (Section 14.5): the set of patient-facing capabilities
    this hospital's WhatsApp number offers (e.g. ["booking","reschedule",
    "cancel","faq"]) -- flows.py's IDLE main menu shows only these. Replaces
    the earlier single-value flow_type (Section 14.1); defaults to an empty
    list (no capabilities enabled) rather than guessing "booking", since an
    empty set is a safe, honest default a caller has to deliberately override,
    not a value that quietly implies functionality nothing configured yet."""
    conn = get_connection()
    offsets_json = json_lib.dumps(reminder_offsets_hours or [24])
    features_json = json_lib.dumps(enabled_features or [])
    portal_password_hash = hash_portal_password(portal_password) if portal_password else None
    cur = conn.execute(
        "INSERT INTO hospitals (name, whatsapp_phone_number_id, meta_access_token_ref, app_secret_ref, "
        "timezone, welcome_message_text, reminder_offsets_hours, reminder_template_name, "
        "data_tier, external_api_base_url, external_api_key, portal_password_hash, enabled_features) "
        "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id",
        (name, whatsapp_phone_number_id, access_token, app_secret, timezone,
         welcome_message_text, offsets_json, reminder_template_name,
         data_tier, external_api_base_url, external_api_key, portal_password_hash, features_json),
    )
    new_id = cur.fetchone()["id"]
    conn.commit()
    return get_hospital(new_id)


def update_hospital(
    hospital_id: int,
    name: str,
    whatsapp_phone_number_id: str,
    access_token: str | None = None,
    app_secret: str | None = None,
    timezone: str = "UTC",
    welcome_message_text: str | None = None,
    reminder_offsets_hours: list[float] | None = None,
    reminder_template_name: str | None = None,
    data_tier: str = "tier1",
    external_api_base_url: str | None = None,
    external_api_key: str | None = None,
    portal_password_hash: str | None = None,
    enabled_features: list[str] | None = None,
) -> Hospital:
    """admin/onboarding.py's tenant edit form -- the only way to correct an
    already-onboarded hospital's stored values (there's no way to change
    departments/doctors here, only the hospitals row itself). Raises
    db.connection.IntegrityError if whatsapp_phone_number_id is changed to a
    value another hospital already uses -- same UNIQUE constraint create_hospital()
    relies on; a hospital keeping its own existing phone_number_id unchanged
    never conflicts with itself. Callers (admin/onboarding.py) are responsible
    for catching it, same as create_hospital().

    portal_password_hash takes an ALREADY-HASHED value (or the hospital's
    existing one, to leave it unchanged) -- unlike create_hospital(), which
    takes a raw password, because the edit route needs to decide whether a
    blank submitted field means "keep current hash" *before* this function
    ever sees it (hashing here would turn a blank field into a real password).

    Deliberately does NOT touch _wa_clients (core/main.py's per-hospital
    WhatsAppClient cache) -- it can't, from here; a hospital whose credentials
    just changed keeps using its OLD cached client until the process restarts.
    See core/main.py's _wa_clients comment and the post-edit confirmation page.

    enabled_features (Section 14.5) defaults to an empty list like
    create_hospital(), but every caller (admin/onboarding.py's edit-tenant
    route, portal.py's settings route) passes the hospital's own current
    value through explicitly -- neither exposes a way to CHANGE which
    features are enabled yet, so an edit to something else must never
    silently reset a tenant's real feature set back to empty."""
    conn = get_connection()
    offsets_json = json_lib.dumps(reminder_offsets_hours or [24])
    features_json = json_lib.dumps(enabled_features or [])
    conn.execute(
        "UPDATE hospitals SET name = ?, whatsapp_phone_number_id = ?, meta_access_token_ref = ?, "
        "app_secret_ref = ?, timezone = ?, welcome_message_text = ?, reminder_offsets_hours = ?, "
        "reminder_template_name = ?, data_tier = ?, external_api_base_url = ?, external_api_key = ?, "
        "portal_password_hash = ?, enabled_features = ? WHERE id = ?",
        (name, whatsapp_phone_number_id, access_token, app_secret, timezone,
         welcome_message_text, offsets_json, reminder_template_name,
         data_tier, external_api_base_url, external_api_key, portal_password_hash, features_json, hospital_id),
    )
    conn.commit()
    return get_hospital(hospital_id)


# --- Departments / doctors ---

def get_departments(hospital_id: int) -> list[dict]:
    conn = get_connection()
    rows = conn.execute(
        "SELECT id, name FROM departments WHERE hospital_id = ? ORDER BY name",
        (hospital_id,),
    ).fetchall()
    return [dict(r) for r in rows]


def find_department(hospital_id: int, department_id: str) -> dict | None:
    conn = get_connection()
    row = conn.execute(
        "SELECT id, name FROM departments WHERE hospital_id = ? AND id = ?",
        (hospital_id, department_id),
    ).fetchone()
    return dict(row) if row else None


def get_doctors(hospital_id: int, department_id: str) -> list[dict]:
    conn = get_connection()
    rows = conn.execute(
        "SELECT id, name FROM doctors WHERE hospital_id = ? AND department_id = ? ORDER BY name",
        (hospital_id, department_id),
    ).fetchall()
    return [dict(r) for r in rows]


def find_doctor(hospital_id: int, department_id: str, doctor_id: str) -> dict | None:
    conn = get_connection()
    row = conn.execute(
        "SELECT id, name FROM doctors WHERE hospital_id = ? AND department_id = ? AND id = ?",
        (hospital_id, department_id, doctor_id),
    ).fetchone()
    return dict(row) if row else None


def create_department(hospital_id: int, name: str) -> dict:
    """id is a UUID-derived opaque string (not a slug of `name`), scoped by an
    h{hospital_id}_ prefix -- avoids both the collision risk of slugifying
    arbitrary user-entered text and the known Tier 1 limitation that
    departments.id is globally unique, not (hospital_id, id) composite-unique
    (db/schema.sql's comment on that table)."""
    department_id = f"h{hospital_id}_{uuid.uuid4().hex[:8]}"
    conn = get_connection()
    conn.execute(
        "INSERT INTO departments (id, hospital_id, name) VALUES (?, ?, ?)",
        (department_id, hospital_id, name),
    )
    conn.commit()
    return {"id": department_id, "name": name}


def create_doctor(
    hospital_id: int,
    department_id: str,
    name: str,
    specialization: str | None = None,
    qualification: str | None = None,
    years_experience: int | None = None,
    working_days: list[str] | None = None,
    working_hours: list[str] | None = None,
    slot_duration_minutes: int = 30,
) -> dict:
    """working_days (e.g. ["Mon", "Wed", "Fri"]) and working_hours (e.g.
    ["10:00-13:00", "17:00-20:00"]) are this doctor's working pattern (Section
    12.1 Step 7) -- generate_slots_for_doctor() is called immediately below to
    produce the initial rolling window of real doctor_slots rows from it
    (Section 12.1.1), so onboarding a doctor through this function is what
    "run slot generation at onboarding submission time" means in practice. A
    doctor with no working_days/working_hours simply generates zero slots."""
    doctor_id = f"h{hospital_id}_{uuid.uuid4().hex[:8]}"
    conn = get_connection()
    conn.execute(
        "INSERT INTO doctors (id, hospital_id, department_id, name, specialization, qualification, "
        "years_experience, working_days, working_hours, slot_duration_minutes) "
        "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        (doctor_id, hospital_id, department_id, name, specialization, qualification,
         years_experience, ",".join(working_days or []), ",".join(working_hours or []), slot_duration_minutes),
    )
    conn.commit()
    generate_slots_for_doctor(hospital_id, doctor_id, conn=conn)
    return {"id": doctor_id, "name": name}


def get_doctor_full(hospital_id: int, doctor_id: str) -> dict | None:
    """Every column, not just {id, name} like get_doctors()/find_doctor() --
    portal.py's doctor-edit form (Section 12.7 follow-up: self-serve doctor
    management) needs the full working pattern to pre-fill, and needs
    department_id from the doctor_id alone (the edit URL only carries the
    doctor's id, not which department it's under)."""
    conn = get_connection()
    row = conn.execute(
        "SELECT id, department_id, name, specialization, qualification, years_experience, "
        "working_days, working_hours, slot_duration_minutes FROM doctors WHERE hospital_id = ? AND id = ?",
        (hospital_id, doctor_id),
    ).fetchone()
    if row is None:
        return None
    d = dict(row)
    d["working_days"] = [x for x in d["working_days"].split(",") if x]
    d["working_hours"] = [x for x in d["working_hours"].split(",") if x]
    return d


def get_all_doctors_for_hospital(hospital_id: int) -> list[dict]:
    """Every doctor at this hospital with its department name attached --
    portal.py's doctors list page (Section 12.7 follow-up), one query instead
    of walking get_departments() -> get_doctors() per department."""
    conn = get_connection()
    rows = conn.execute(
        "SELECT doc.id, doc.department_id, d.name AS department_name, doc.name, doc.specialization "
        "FROM doctors doc JOIN departments d ON d.id = doc.department_id "
        "WHERE doc.hospital_id = ? ORDER BY d.name, doc.name",
        (hospital_id,),
    ).fetchall()
    return [dict(r) for r in rows]


def update_doctor(
    hospital_id: int,
    doctor_id: str,
    name: str,
    specialization: str | None = None,
    qualification: str | None = None,
    years_experience: int | None = None,
    working_days: list[str] | None = None,
    working_hours: list[str] | None = None,
    slot_duration_minutes: int = 30,
) -> dict | None:
    """portal.py's doctor-edit form. Returns None if no such doctor exists at
    this hospital (nothing updated), same "hospital_id in the WHERE clause is
    the actual guard, not application logic" discipline as every other
    hospital-scoped write here.

    Regenerates this doctor's ENTIRE doctor_slots window from scratch against
    the (possibly changed) working pattern, rather than trying to reconcile
    old vs. new slots row by row -- safe to do because doctor_slots carries no
    foreign key from appointments (get_slots() matches them only by
    scheduled_at string equality, see that function's docstring), so dropping
    and rebuilding a doctor's still-just-offered slots never touches an
    appointment a patient has already booked."""
    conn = get_connection()
    cur = conn.execute(
        "UPDATE doctors SET name = ?, specialization = ?, qualification = ?, years_experience = ?, "
        "working_days = ?, working_hours = ?, slot_duration_minutes = ? WHERE hospital_id = ? AND id = ?",
        (name, specialization, qualification, years_experience,
         ",".join(working_days or []), ",".join(working_hours or []), slot_duration_minutes,
         hospital_id, doctor_id),
    )
    if cur.rowcount == 0:
        return None
    conn.execute("DELETE FROM doctor_slots WHERE hospital_id = ? AND doctor_id = ?", (hospital_id, doctor_id))
    conn.commit()
    generate_slots_for_doctor(hospital_id, doctor_id, conn=conn)
    return {"id": doctor_id, "name": name}


def list_doctor_ids(hospital_id: int) -> list[str]:
    """Used by the slot top-up job (slots/scheduler.py) to loop every doctor
    at a hospital without needing to walk departments first."""
    conn = get_connection()
    rows = conn.execute("SELECT id FROM doctors WHERE hospital_id = ?", (hospital_id,)).fetchall()
    return [r["id"] for r in rows]


def _parse_time_range(time_range: str) -> tuple[str, str]:
    start, end = time_range.split("-")
    return start.strip(), end.strip()


def generate_slots_for_doctor(
    hospital_id: int,
    doctor_id: str,
    days_ahead: int = _SLOT_DAYS_AHEAD,
    now: date | None = None,
    conn=None,
) -> int:
    """Generates real doctor_slots rows for the next `days_ahead` days (Section
    12.1.1) from this doctor's stored working_days/working_hours/
    slot_duration_minutes. ON CONFLICT DO NOTHING against doctor_slots' UNIQUE
    (doctor_id, scheduled_at) (db/schema.sql) is what makes this idempotent --
    calling it again for a window that's already partly populated (the
    periodic top-up job, slots/scheduler.py) only adds the new days, never
    duplicates existing ones. Returns the number of *new* slot rows inserted.

    conn is an optional explicit connection (rather than get_connection())
    because db/seed.py calls this against a connection it's still assembling,
    before db.connection's shared connection has been repointed to it."""
    conn = conn or get_connection()
    doctor_row = conn.execute(
        "SELECT working_days, working_hours, slot_duration_minutes FROM doctors WHERE hospital_id = ? AND id = ?",
        (hospital_id, doctor_id),
    ).fetchone()
    if doctor_row is None:
        return 0

    working_days = {d.strip() for d in doctor_row["working_days"].split(",") if d.strip()}
    working_hours = [h.strip() for h in doctor_row["working_hours"].split(",") if h.strip()]
    slot_duration = doctor_row["slot_duration_minutes"]
    if not working_days or not working_hours or not slot_duration:
        return 0

    today = now or date.today()
    candidates: list[tuple] = []
    for i in range(1, days_ahead + 1):
        d = today + timedelta(days=i)
        if _WEEKDAY_ABBREVS[d.weekday()] not in working_days:
            continue
        for time_range in working_hours:
            start_str, end_str = _parse_time_range(time_range)
            current = datetime.combine(d, datetime.strptime(start_str, "%H:%M").time())
            end = datetime.combine(d, datetime.strptime(end_str, "%H:%M").time())
            step = timedelta(minutes=slot_duration)
            while current + step <= end:
                candidates.append((hospital_id, doctor_id, current.isoformat()))
                current += step

    if not candidates:
        return 0

    # One multi-row INSERT instead of one round-trip per slot -- this used to
    # be a per-slot conn.execute() in a loop, which against a real (non-local)
    # Postgres like Neon meant one network round-trip per slot: a doctor with
    # even a single ordinary shift over a 14-day window is 100+ slots, so
    # onboarding a hospital with a few doctors could take tens of seconds just
    # here. Building one INSERT with all rows' worth of "(?, ?, ?)" placeholders
    # (well within Postgres's ~65535 parameter limit for any realistic doctor
    # count/window) turns that into a single round-trip per doctor.
    placeholders = ", ".join(["(?, ?, ?)"] * len(candidates))
    flat_params = [value for row in candidates for value in row]
    cur = conn.execute(
        f"INSERT INTO doctor_slots (hospital_id, doctor_id, scheduled_at) VALUES {placeholders} "
        "ON CONFLICT (doctor_id, scheduled_at) DO NOTHING",
        flat_params,
    )
    inserted = cur.rowcount
    conn.commit()
    return inserted


# --- Slots (real, persisted rows — see module docstring) ---

def get_slots(hospital_id: int, doctor_id: str) -> list[dict]:
    """This doctor's generated doctor_slots rows, minus any that already have a
    *booked* appointment at that exact time (Phase 8: an already-taken slot
    must never be offered to another patient)."""
    conn = get_connection()
    booked_rows = conn.execute(
        "SELECT scheduled_at FROM appointments WHERE hospital_id = ? AND doctor_id = ? AND status = ?",
        (hospital_id, doctor_id, STATUS_BOOKED),
    ).fetchall()
    booked_at = {row["scheduled_at"] for row in booked_rows}

    slot_rows = conn.execute(
        "SELECT scheduled_at FROM doctor_slots WHERE hospital_id = ? AND doctor_id = ? ORDER BY scheduled_at",
        (hospital_id, doctor_id),
    ).fetchall()

    slots = []
    for row in slot_rows:
        scheduled_at_iso = row["scheduled_at"]
        if scheduled_at_iso in booked_at:
            continue
        dt = datetime.fromisoformat(scheduled_at_iso)
        slots.append({
            "id": scheduled_at_iso,
            "date": dt.date().isoformat(),
            "time": dt.strftime("%H:%M"),
            "label": f"{dt.strftime('%a %d %b')} {dt.strftime('%H:%M')}",
        })
    return slots


def find_slot(hospital_id: int, doctor_id: str, slot_id: str) -> dict | None:
    for s in get_slots(hospital_id, doctor_id):
        if s["id"] == slot_id:
            return s
    return None


# --- Appointments ---

def create_appointment(
    hospital_id: int,
    phone: str,
    department_id: str,
    doctor_id: str,
    scheduled_at: datetime,
) -> Appointment:
    """Raises db.connection.IntegrityError if this doctor already has a
    *booked* appointment at this exact scheduled_at (db/schema.sql's partial
    unique index) — that's the actual double-booking guard, not application
    logic. Catching it gracefully is Phase 8 work, not done here."""
    conn = get_connection()
    cur = conn.execute(
        "INSERT INTO appointments (hospital_id, phone, department_id, doctor_id, scheduled_at) "
        "VALUES (?, ?, ?, ?, ?) RETURNING id",
        (hospital_id, phone, department_id, doctor_id, scheduled_at.isoformat()),
    )
    new_id = cur.fetchone()["id"]
    conn.commit()
    return get_appointment(hospital_id, new_id)


def get_appointment(hospital_id: int, appointment_id: int) -> Appointment | None:
    conn = get_connection()
    row = conn.execute(
        _APPOINTMENT_SELECT + " WHERE a.id = ? AND a.hospital_id = ?",
        (appointment_id, hospital_id),
    ).fetchone()
    return _row_to_appointment(row) if row else None


def get_upcoming_appointments_for_phone(hospital_id: int, phone: str, now: datetime | None = None) -> list[Appointment]:
    """A patient's own future, still-booked appointments — soonest first.
    Past appointments and ones already cancelled/rescheduled are excluded here
    (not filtered later) so callers never have to remember to check status."""
    now = now or datetime.now()
    conn = get_connection()
    rows = conn.execute(
        _APPOINTMENT_SELECT + " WHERE a.hospital_id = ? AND a.phone = ? AND a.status = ? AND a.scheduled_at > ? "
        "ORDER BY a.scheduled_at ASC",
        (hospital_id, phone, STATUS_BOOKED, now.isoformat()),
    ).fetchall()
    return [_row_to_appointment(r) for r in rows]


def get_upcoming_appointments(hospital_id: int, offset_hours: float, now: datetime | None = None) -> list[Appointment]:
    """Still-booked appointments scheduled between `now` and `now + offset_hours`
    that haven't had a reminder sent yet *for this specific offset* — a hospital
    can configure multiple offsets (SPEC Section 4's reminder_offsets_hours, e.g.
    24h-before AND 1h-before), each tracked independently via appointment_reminders
    so configuring more than one actually results in more than one reminder per
    appointment, rather than the first one sent silently blocking the rest.
    Used by reminders/scheduler.py, once per offset."""
    now = now or datetime.now()
    cutoff = now + timedelta(hours=offset_hours)
    conn = get_connection()
    rows = conn.execute(
        _APPOINTMENT_SELECT + """
        WHERE a.hospital_id = ? AND a.status = ?
          AND a.scheduled_at >= ? AND a.scheduled_at <= ?
          AND NOT EXISTS (
              SELECT 1 FROM appointment_reminders ar
              WHERE ar.appointment_id = a.id AND ar.offset_hours = ?
          )
        ORDER BY a.scheduled_at ASC
        """,
        (hospital_id, STATUS_BOOKED, now.isoformat(), cutoff.isoformat(), offset_hours),
    ).fetchall()
    return [_row_to_appointment(r) for r in rows]


def get_all_appointments_for_hospital(hospital_id: int, limit: int = 500) -> list[Appointment]:
    """Every appointment (any status) for a hospital's own bookings dashboard
    (portal.py, Tier 1 self-serve view) -- most recently scheduled first.
    Unlike get_upcoming_appointments_for_phone()/get_upcoming_appointments(),
    this is intentionally not filtered to booked/future-only: hospital staff
    reviewing their own bookings want to see cancellations/reschedules too."""
    conn = get_connection()
    rows = conn.execute(
        _APPOINTMENT_SELECT + " WHERE a.hospital_id = ? ORDER BY a.scheduled_at DESC LIMIT ?",
        (hospital_id, limit),
    ).fetchall()
    return [_row_to_appointment(r) for r in rows]


def mark_reminded(hospital_id: int, appointment_id: int, offset_hours: float) -> None:
    """Records that the reminder for this specific offset has been sent.
    ON CONFLICT DO NOTHING + appointment_reminders' UNIQUE(appointment_id, offset_hours)
    (db/schema.sql) means calling this twice for the same offset is a safe no-op,
    not a duplicate record — that constraint is the actual no-double-send
    guarantee, same pattern as the double-booking index from Phase 8."""
    conn = get_connection()
    conn.execute(
        "INSERT INTO appointment_reminders (hospital_id, appointment_id, offset_hours) VALUES (?, ?, ?) "
        "ON CONFLICT (appointment_id, offset_hours) DO NOTHING",
        (hospital_id, appointment_id, offset_hours),
    )
    conn.commit()


def get_reminded_offsets(hospital_id: int, appointment_id: int) -> list[float]:
    """Which reminder offsets (in hours) have already fired for this appointment."""
    conn = get_connection()
    rows = conn.execute(
        "SELECT offset_hours FROM appointment_reminders WHERE hospital_id = ? AND appointment_id = ? ORDER BY offset_hours DESC",
        (hospital_id, appointment_id),
    ).fetchall()
    return [r["offset_hours"] for r in rows]


def cancel_appointment(hospital_id: int, appointment_id: int) -> None:
    """Marks the appointment cancelled — does not delete the row, so
    cancellation history/audit trail isn't lost."""
    conn = get_connection()
    conn.execute(
        "UPDATE appointments SET status = ? WHERE id = ? AND hospital_id = ?",
        (STATUS_CANCELLED, appointment_id, hospital_id),
    )
    conn.commit()


def mark_rescheduled(hospital_id: int, appointment_id: int) -> None:
    """Marks the old appointment as superseded by a reschedule — does not
    delete the row. Callers are responsible for create_appointment()-ing the
    new slot separately (see core/booking_flow.py's reschedule confirm)."""
    conn = get_connection()
    conn.execute(
        "UPDATE appointments SET status = ? WHERE id = ? AND hospital_id = ?",
        (STATUS_RESCHEDULED, appointment_id, hospital_id),
    )
    conn.commit()


# --- FAQ topics (SPEC Section 14.2, the FAQ flow_type's entire data model) ---

def get_faq_topics(hospital_id: int) -> list[dict]:
    """faq_flow.py's topic menu (Section 14.2) -- ordered by display_order,
    then id as a tiebreaker (display_order isn't unique, ties are expected)."""
    conn = get_connection()
    rows = conn.execute(
        "SELECT id, topic_label, answer_text, display_order FROM faq_topics "
        "WHERE hospital_id = ? ORDER BY display_order, id",
        (hospital_id,),
    ).fetchall()
    return [dict(r) for r in rows]


def find_faq_topic(hospital_id: int, topic_id: str) -> dict | None:
    """topic_id arrives as a WhatsApp interactive-reply id (always a string)
    -- faq_topics.id is a SERIAL int, so a non-numeric/stale/cross-hospital id
    (e.g. a leftover tap from before a flow_type switch) safely resolves to
    "not found" rather than a raw ValueError from the int() conversion."""
    try:
        topic_id_int = int(topic_id)
    except (TypeError, ValueError):
        return None
    conn = get_connection()
    row = conn.execute(
        "SELECT id, topic_label, answer_text, display_order FROM faq_topics "
        "WHERE hospital_id = ? AND id = ?",
        (hospital_id, topic_id_int),
    ).fetchone()
    return dict(row) if row else None


def create_faq_topic(
    hospital_id: int, topic_label: str, answer_text: str, display_order: int | None = None,
) -> dict:
    """admin/onboarding.py's wizard Step 7 topic/answer builder (Section 14.3,
    faq-flow tenants only). display_order defaults to "append at the end" of
    this hospital's existing topics, so onboarding-time topics keep the order
    they were entered in without the caller having to compute indices itself."""
    conn = get_connection()
    if display_order is None:
        row = conn.execute(
            "SELECT COALESCE(MAX(display_order), -1) + 1 AS next_order FROM faq_topics WHERE hospital_id = ?",
            (hospital_id,),
        ).fetchone()
        display_order = row["next_order"]
    cur = conn.execute(
        "INSERT INTO faq_topics (hospital_id, topic_label, answer_text, display_order) "
        "VALUES (?, ?, ?, ?) RETURNING id",
        (hospital_id, topic_label, answer_text, display_order),
    )
    new_id = cur.fetchone()["id"]
    conn.commit()
    return {"id": new_id, "topic_label": topic_label, "answer_text": answer_text, "display_order": display_order}
